[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [6]:
# 파이썬 랜덤함수 Python random
import random
print(random.random(), '\n')  # [0,1) 사이의 난수
print(random.randint(1,10), '\n') # [1,10] 사이의 정수
print(random.uniform(10,20), '\n') # min, max 사이의 flost 
print(random.randrange(10), '\n') # 지정 범위 내 int
print(random.choice([1,2,3,4,5]), '\n') # 리스트 내부의 요소를 랜덤 선택
li = [1,2,3,4,5]
print(random.sample(li,3), '\n') # 리스트 요소를 중복이 안되게 출력
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.4308653611791674 

9 

13.83592287751478 

7 

4 

[1, 5, 2] 

[4, 1, 5, 2, 3]


In [1]:
import numpy as np
r = np.random.rand(10000000) # 0~1 사이의 균일 분포  
#print(r)
r.mean() #백만개의 평균

0.4999841134863574

In [15]:
# 표준 정규분포
r = np.random.randn(10000) # 표준 정규분포
print(r, '\n')
r.mean()

[ 0.2528009   0.14030304 -0.21561132 ...  1.46223741  0.3500009
 -0.71322247] 



-0.0065856617189130875

In [16]:
np.random.uniform(1.0,2.0,10)  # (min, max , 배열 (개수))

array([1.62134148, 1.76455944, 1.82008531, 1.86854738, 1.11646126,
       1.7765836 , 1.80336616, 1.90835825, 1.35629645, 1.68528172])

In [17]:
np.random.uniform(0,1,(2,3))  # 사이즈로 행렬 가능 

array([[0.77269758, 0.7354887 , 0.73417593],
       [0.21868014, 0.11045541, 0.86615468]])

In [18]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최솟갑, 최댓값을 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.5568133 , 0.38188314, 0.35705068],
       [0.40932502, 0.23771244, 0.75023978]])

In [2]:
import pandas as pd
ar = np.random.rand(4,8)
ar

array([[0.20192273, 0.29856601, 0.00656741, 0.67119533, 0.7058276 ,
        0.0360917 , 0.00781923, 0.34008918],
       [0.67776524, 0.91459003, 0.69141984, 0.06415064, 0.9404211 ,
        0.64563825, 0.14600817, 0.56716404],
       [0.20997413, 0.48784717, 0.37243684, 0.34377504, 0.52799673,
        0.45817264, 0.33402699, 0.95193898],
       [0.98678627, 0.92655353, 0.02858976, 0.98877482, 0.642186  ,
        0.08559645, 0.33969063, 0.35710627]])

In [139]:
# 배열을 df로 변환
# columns 8개에 대한 이름
#columns = ['id','gender','age','region','product','price','qty','time']
df = pd.DataFrame(ar)
df.columns = ['id','gender','age','region','product','price','qty','time']
df

id    gender       age    region   product     price       qty  \
0  0.341556  0.534465  0.419971  0.880354  0.570342  0.592746  0.547197   
1  0.032774  0.780731  0.066376  0.925660  0.470460  0.334332  0.024771   
2  0.068612  0.353690  0.928986  0.351830  0.585392  0.090067  0.001641   
3  0.442020  0.160220  0.641796  0.959302  0.077348  0.361543  0.625626   

       time  
0  0.833175  
1  0.308567  
2  0.259335  
3  0.905091

In [51]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3를 출력하세요.

In [64]:
df['id'] = df.index
# df.set_index('id', inplace=True)
df['gender'] = (np.random.choice(['male','female'],4))
df['age'] = (np.random.randint(1,120,4))
df3 = df[['id','gender','age']]
df3

id  gender  age
0   0    male   35
1   1    male   98
2   2    male   85
3   3  female   72

In [67]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_ar = np.random.randn(100000000) # 정규분포 
large_ar.sort()

In [68]:
large_ar[int(0.5*len(large_ar))]

-5.354641075157349e-06

In [72]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [73]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [74]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [78]:
# 배열 데이터릐 입출력
ar = np.arange(10)
np.save('some_ar', ar)

In [79]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('ar_archive.npz', a=ar, b=ar)

In [82]:
arch = np.load('ar_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a = np.arange(1,10)
print(a, '\n')
np.argsort(a)  # 인덱스 정렬? 출력

[1 2 3 4 5 6 7 8 9] 



array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [84]:
# 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]  # 시작 인덱스 -1 생략됨

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [99]:
np.argsort(a)[-1::-1]  

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

# 도전과제 7/6
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요. (99의 위치)
- np.arange(4)를 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


In [3]:
import warnings
warnings.filterwarnings('ignore')

In [188]:
arr = np.arange(336).reshape(6,7,8)


arr_w = np.where(arr == 99)
arr_w
print(arr_w)
print(arr[1,5,3])

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))
99


In [180]:
ar = np.zeros((5,5))
arr = np.arange(1,5).reshape(-1)
for i in range(0,4):
    ar[i+1,i] = arr[i]
ar
# [1::,:3:]

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [114]:
# Q. 0 ~ 10 정수 (5,5) 행렬의 역행렬을 구한 후 두 행렬간의 행렬곱을 구하세요.
arr2d = np.random.randint(0,10,(5,5))
arr2d_r = np.linalg.inv(arr2d)
#arr2d * arr2d_r
np.dot(arr2d, arr2d_r)

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00,
         0.00000000e+00, -5.55111512e-17],
       [-1.80411242e-16,  1.00000000e+00,  0.00000000e+00,
        -3.33066907e-16, -5.55111512e-17],
       [-1.31838984e-16,  8.32667268e-17,  1.00000000e+00,
        -5.55111512e-17,  1.38777878e-16],
       [-1.11022302e-16, -2.22044605e-16,  0.00000000e+00,
         1.00000000e+00,  4.44089210e-16],
       [-2.08166817e-17, -2.77555756e-17, -1.11022302e-16,
        -5.55111512e-17,  1.00000000e+00]])

# 과제 7/6

### 아래 가이드에 따라서 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1천 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터

- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성

- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요
우리 데이터셋은 id 와 고객번호가 1:1 대응임 id 삭제 
 10살 미만은 거래가 불가능 할것 이라고 보고 재설정함 10~80
1.지역에 따른 구매금액비교 >>>> 부유한 지역 확인1,2,3,4
2.나이(20대 30대, 40대, 50대) 와 성별로 구매금액 비교 >>> 가장 구매력 좋은 연령대와 성별 30대 여성 40대 여성, 가장 구매력이 낮은 60대 이상 남자
3.21년도와 20년도의 총 매출하락과, 고가제품 구매율상승  >>경제상황 분석 빈익빈 부익부
4.
 5.고가제품 구매 연령 2,30대 젊은층 큼, 저가제품(식료품) 주부 구매

ex) 데이터 수정 후 비교분석 전년도 대비 고가제품 구매율이 15% 상승했다. 
필요에 따라 데이터 더 만들어도 됨 날짜나 시간대
구룹핑, 범주화, 연령대별 구매력, 소득수준 높은지역, 구매상품별 구매증감 등 
#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.
플롯 그룹핑 범주화 피벗 ~~!@ㅣㅏㅓㅇ리ㅏㅇㄴ머림



In [53]:

np.random.seed(1)
df_c = pd.DataFrame(columns=['id','cusno','gender','age','region'])
df_c['id'] = random.sample(range(1,10001), 10000)
df_c['cusno'] = np.random.randint(10001, 11001, 10000)
df_c['gender'] = np.random.randint(0,2, 10000)
df_c['age'] = np.random.randint(0,81, 10000)
df_c['region'] = np.random.randint(1,11, 10000)
df_c.head()

id  cusno  gender  age  region
0  6312  10038       1   36       8
1  6891  10236       0   45       8
2   664  10909       1    9       7
3  4243  10073       1   13       7
4  8377  10768       0   58       9

In [54]:
np.random.seed(1)
df_d = pd.DataFrame(columns=['product_20','product_21','price_20','price_21','quantity_20','quantity_21','amount_20','amount_21','sales'])
df_d['product_20'] = np.random.choice((10, 20, 30), 10000)
df_d['product_21'] = np.random.choice((10, 20, 30), 10000)
df_d['price_20'] = np.random.uniform(1000,50001, 10000)
df_d['price_21'] = np.random.uniform(1000,50001, 10000)
df_d['quantity_20'] = np.random.randint(1,101, 10000)
df_d['quantity_21'] = np.random.randint(1,101, 10000)
df_d['amount_20'] = df_d.price_20 * df_d.quantity_20
df_d['amount_21'] = df_d.price_21 * df_d.quantity_21

#df_d['sales'] =  df_d.amount_20-df_d.amount_21
# def f(x):
#     if x > 0 :
#         return 1
#     else:
#         return 0
# df_d.sales = df_d.sales.apply(f)

# np.where(df. 컬럼명 조건, 1, 0)  트루 1 출력 펄스 2 출력 


df_d.head()

product_20  product_21      price_20      price_21  quantity_20  \
0          20          10  33467.832932  32770.509048           54   
1          10          10  14172.262317  19010.415916           90   
2          10          20  44448.283850  30644.908093           89   
3          20          20  32926.667667  23319.429068           78   
4          20          30   8969.172198  44005.463441           29   

   quantity_21     amount_20     amount_21 sales  
0            5  1.807263e+06  1.638525e+05   NaN  
1           30  1.275504e+06  5.703125e+05   NaN  
2           30  3.955897e+06  9.193472e+05   NaN  
3           57  2.568280e+06  1.329207e+06   NaN  
4            8  2.601060e+05  3.520437e+05   NaN

In [55]:
df = df_c.join(df_d, how='inner')
df

id  cusno  gender  age  region  product_20  product_21      price_20  \
0     6312  10038       1   36       8          20          10  33467.832932   
1     6891  10236       0   45       8          10          10  14172.262317   
2      664  10909       1    9       7          10          20  44448.283850   
3     4243  10073       1   13       7          20          20  32926.667667   
4     8377  10768       0   58       9          20          30   8969.172198   
...    ...    ...     ...  ...     ...         ...         ...           ...   
9995  9879  10685       1   25       2          10          20  29770.540937   
9996   422  10249       0   66       2          10          30  44284.851498   
9997  7060  10534       1   47       4          20          30   5816.217198   
9998  3632  10990       1   64       9          10          10  23527.476318   
9999  9771  10126       0   49       1          30          20  11355.832431   

          price_21  quantity_20  quantity_21     amount_20     amount_21 sales  
0     32770.509048           54            5  1.807263e+06  1.638525e+05   NaN  
1     19010.415916           90           30  1.275504e+06  5.703125e+05   NaN  
2     30644.908093           89           30  3.955897e+06  9.193472e+05   NaN  
3     23319.429068           78           57  2.568280e+06  1.329207e+06   NaN  
4     44005.463441           29            8  2.601060e+05  3.520437e+05   NaN  
...            ...          ...          ...           ...           ...   ...  
9995  15477.064079           96           28  2.857972e+06  4.333578e+05   NaN  
9996  24724.416439           58           89  2.568521e+06  2.200473e+06   NaN  
9997  45734.030117            8           37  4.652974e+04  1.692159e+06   NaN  
9998  27245.857202           58           98  1.364594e+06  2.670094e+06   NaN  
9999  13717.620481           15           29  1.703375e+05  3.978110e+05   NaN  

[10000 rows x 14 columns]

# 거래일자, 요일, 시간을 추가해서 10000개의 관측치를 갖는 데이터셋을 만드세요

In [56]:
import numpy as np
import pandas as pd
import random
import time
import datetime

In [57]:
#거래일자
random.seed(0)
df['date'] = np.random.choice(pd.date_range(start='2020-10-01', end='2021-12-31'), 10000)
df.date = pd.to_datetime(df.date)


In [58]:
#거래 시간
df['time'] = np.random.randint(10,20 , 10000)


In [59]:
df.drop('sales', axis=1, inplace=True)
df

id  cusno  gender  age  region  product_20  product_21      price_20  \
0     6312  10038       1   36       8          20          10  33467.832932   
1     6891  10236       0   45       8          10          10  14172.262317   
2      664  10909       1    9       7          10          20  44448.283850   
3     4243  10073       1   13       7          20          20  32926.667667   
4     8377  10768       0   58       9          20          30   8969.172198   
...    ...    ...     ...  ...     ...         ...         ...           ...   
9995  9879  10685       1   25       2          10          20  29770.540937   
9996   422  10249       0   66       2          10          30  44284.851498   
9997  7060  10534       1   47       4          20          30   5816.217198   
9998  3632  10990       1   64       9          10          10  23527.476318   
9999  9771  10126       0   49       1          30          20  11355.832431   

          price_21  quantity_20  quantity_21     amount_20     amount_21  \
0     32770.509048           54            5  1.807263e+06  1.638525e+05   
1     19010.415916           90           30  1.275504e+06  5.703125e+05   
2     30644.908093           89           30  3.955897e+06  9.193472e+05   
3     23319.429068           78           57  2.568280e+06  1.329207e+06   
4     44005.463441           29            8  2.601060e+05  3.520437e+05   
...            ...          ...          ...           ...           ...   
9995  15477.064079           96           28  2.857972e+06  4.333578e+05   
9996  24724.416439           58           89  2.568521e+06  2.200473e+06   
9997  45734.030117            8           37  4.652974e+04  1.692159e+06   
9998  27245.857202           58           98  1.364594e+06  2.670094e+06   
9999  13717.620481           15           29  1.703375e+05  3.978110e+05   

           date  time  
0    2021-11-28    15  
1    2020-10-19    19  
2    2021-06-28    13  
3    2021-05-22    14  
4    2021-01-08    15  
...         ...   ...  
9995 2021-03-05    12  
9996 2021-12-21    19  
9997 2021-05-31    11  
9998 2021-06-04    19  
9999 2021-02-14    12  

[10000 rows x 15 columns]

In [60]:
# 특정요일 구하기
import datetime
# def get_yoil(x):
#     days = ['MON','TUE','WED','THU','FRI','SAT','SUN']
#     for i in x:
#           return days[i.weekday()]
# df['week'] = get_yoil(df.date)
# df.drop('sales', axis=1, inplace=True)
# df
#2. day(요일) 
df['week']=df['date'].apply(lambda x: x.weekday())  #date별 요일을 숫자로 나타냄
df['week']=df['week'].replace(list(range(7)),['월','화','수','목','금','토','일'])
#df.drop('day', axis=1, inplace=True)
df


id  cusno  gender  age  region  product_20  product_21      price_20  \
0     6312  10038       1   36       8          20          10  33467.832932   
1     6891  10236       0   45       8          10          10  14172.262317   
2      664  10909       1    9       7          10          20  44448.283850   
3     4243  10073       1   13       7          20          20  32926.667667   
4     8377  10768       0   58       9          20          30   8969.172198   
...    ...    ...     ...  ...     ...         ...         ...           ...   
9995  9879  10685       1   25       2          10          20  29770.540937   
9996   422  10249       0   66       2          10          30  44284.851498   
9997  7060  10534       1   47       4          20          30   5816.217198   
9998  3632  10990       1   64       9          10          10  23527.476318   
9999  9771  10126       0   49       1          30          20  11355.832431   

          price_21  quantity_20  quantity_21     amount_20     amount_21  \
0     32770.509048           54            5  1.807263e+06  1.638525e+05   
1     19010.415916           90           30  1.275504e+06  5.703125e+05   
2     30644.908093           89           30  3.955897e+06  9.193472e+05   
3     23319.429068           78           57  2.568280e+06  1.329207e+06   
4     44005.463441           29            8  2.601060e+05  3.520437e+05   
...            ...          ...          ...           ...           ...   
9995  15477.064079           96           28  2.857972e+06  4.333578e+05   
9996  24724.416439           58           89  2.568521e+06  2.200473e+06   
9997  45734.030117            8           37  4.652974e+04  1.692159e+06   
9998  27245.857202           58           98  1.364594e+06  2.670094e+06   
9999  13717.620481           15           29  1.703375e+05  3.978110e+05   

           date  time week  
0    2021-11-28    15    일  
1    2020-10-19    19    월  
2    2021-06-28    13    월  
3    2021-05-22    14    토  
4    2021-01-08    15    금  
...         ...   ...  ...  
9995 2021-03-05    12    금  
9996 2021-12-21    19    화  
9997 2021-05-31    11    월  
9998 2021-06-04    19    금  
9999 2021-02-14    12    일  

[10000 rows x 16 columns]

In [61]:
df.columns

Index(['id', 'cusno', 'gender', 'age', 'region', 'product_20', 'product_21',
       'price_20', 'price_21', 'quantity_20', 'quantity_21', 'amount_20',
       'amount_21', 'date', 'time', 'week'],
      dtype='object')

In [62]:
#id 인덱스화
df.id = np.sort(df.id)
df.set_index('id',inplace=True)
df

cusno  gender  age  region  product_20  product_21      price_20  \
id                                                                        
1      10038       1   36       8          20          10  33467.832932   
2      10236       0   45       8          10          10  14172.262317   
3      10909       1    9       7          10          20  44448.283850   
4      10073       1   13       7          20          20  32926.667667   
5      10768       0   58       9          20          30   8969.172198   
...      ...     ...  ...     ...         ...         ...           ...   
9996   10685       1   25       2          10          20  29770.540937   
9997   10249       0   66       2          10          30  44284.851498   
9998   10534       1   47       4          20          30   5816.217198   
9999   10990       1   64       9          10          10  23527.476318   
10000  10126       0   49       1          30          20  11355.832431   

           price_21  quantity_20  quantity_21     amount_20     amount_21  \
id                                                                          
1      32770.509048           54            5  1.807263e+06  1.638525e+05   
2      19010.415916           90           30  1.275504e+06  5.703125e+05   
3      30644.908093           89           30  3.955897e+06  9.193472e+05   
4      23319.429068           78           57  2.568280e+06  1.329207e+06   
5      44005.463441           29            8  2.601060e+05  3.520437e+05   
...             ...          ...          ...           ...           ...   
9996   15477.064079           96           28  2.857972e+06  4.333578e+05   
9997   24724.416439           58           89  2.568521e+06  2.200473e+06   
9998   45734.030117            8           37  4.652974e+04  1.692159e+06   
9999   27245.857202           58           98  1.364594e+06  2.670094e+06   
10000  13717.620481           15           29  1.703375e+05  3.978110e+05   

            date  time week  
id                           
1     2021-11-28    15    일  
2     2020-10-19    19    월  
3     2021-06-28    13    월  
4     2021-05-22    14    토  
5     2021-01-08    15    금  
...          ...   ...  ...  
9996  2021-03-05    12    금  
9997  2021-12-21    19    화  
9998  2021-05-31    11    월  
9999  2021-06-04    19    금  
10000 2021-02-14    12    일  

[10000 rows x 15 columns]

# 조작하고 인사이트 세가지는 뽑아오셈 

로우데이터를 먼저 만들고
구매감소고객을 찾고 이유, 
구매감소에 관련된 컬럼을 조작해야겠지 독립변수

label로 학습
구매 증가 감소 도출할 수 있음

고객별
인사이트
행동패턴, 
저가품, 일회용품 감소, 고가품 증가 보복소비?

남성 여성, 여성의 구매가 줄었음



1.랜덤으로 돌려서 저가품의 가격이 고가품 가격보다 높은 경우가 생김

In [ ]:
# 저가품의 가격과 고가품의 가격 매치
bin_d = np.linspace(sal.price_20.min(), sal.price_20.max(), 4)
bin_n = ['10','20','30']
df['product_20'] = pd.cut(x=df.price_20,  
                           bins=bin_d,  
                           labels=bin_n, 
                           include_lowest=True)  
bin_d = np.linspace(sal.price_21.min(), sal.price_21.max(), 4)
df['product_21'] = pd.cut(x=df.price_21,  
                           bins=bin_d,  
                           labels=bin_n, 
                           include_lowest=True)  

In [63]:


# 구매감소고객
df1 = df[(df['amount_20']>df['amount_21'])]
df1

# 구매 감소 고객 중에 고가품 구매 증가 고객 
df2 = df1[df1['product_20']<df1['product_21']]
df2

cusno  gender  age  region  product_20  product_21      price_20  \
id                                                                       
1     10038       1   36       8          20          10  33467.832932   
8     10646       1   59       9          20          10  11116.814156   
13    10973       1   48       4          20          10  11491.391170   
14    10584       0   79       9          30          10  23343.793386   
18    10282       1   70       2          30          10  18605.206051   
...     ...     ...  ...     ...         ...         ...           ...   
9971  10214       1   35       8          30          10  39808.703063   
9981  10119       1   44       3          20          10  27902.345162   
9992  10950       0   72       2          30          20  29127.852830   
9994  10035       0   50       9          30          20  28882.497802   
9995  10444       0   20       8          30          20  35812.176006   

          price_21  quantity_20  quantity_21     amount_20     amount_21  \
id                                                                         
1     32770.509048           54            5  1.807263e+06  1.638525e+05   
8      4232.160071           63           47  7.003593e+05  1.989115e+05   
13     3880.477561           22           15  2.528106e+05  5.820716e+04   
14     9560.265297           23           24  5.369072e+05  2.294464e+05   
18    44358.392548           22            2  4.093145e+05  8.871679e+04   
...            ...          ...          ...           ...           ...   
9971   3168.638902           63           50  2.507948e+06  1.584319e+05   
9981  11422.893145           73            6  2.036871e+06  6.853736e+04   
9992   4062.512930            5           21  1.456393e+05  8.531277e+04   
9994  22519.279503           67           57  1.935127e+06  1.283599e+06   
9995  45384.630675           16            3  5.729948e+05  1.361539e+05   

           date  time week  
id                          
1    2021-11-28    15    일  
8    2021-10-04    10    월  
13   2020-11-07    10    토  
14   2020-11-19    11    목  
18   2020-10-03    17    토  
...         ...   ...  ...  
9971 2021-02-26    17    금  
9981 2021-08-17    11    화  
9992 2021-01-29    12    금  
9994 2021-07-22    19    목  
9995 2021-12-29    11    수  

[1705 rows x 15 columns]

In [37]:

# 10세 미만은 구매를 안할 것을 ㅗ보고 10~80으로 데이터 변환

df['age'] = np.random.randint(10,81, 1000)
df

cusno  gender  age  region  product_20  product_21      price_20  \
0      827       1   23       5          20          20  47358.786699   
1      504       0   59       8          20          10  46074.212780   
2      399       1   26       1          10          30  33794.033492   
3      748       1   19      10          20          20  17605.025554   
4      226       1   58       1          20          30  23692.594117   
..     ...     ...  ...     ...         ...         ...           ...   
995    978       0   52       8          20          30  34618.604804   
996    578       1   59      10          30          20   6992.622037   
997    541       0   30       5          20          10  22605.730592   
998    616       1   29       2          10          10  16467.342294   
999    380       0   75       7          10          20  25399.795566   

         price_21  quantity_20  quantity_21     amount_20     amount_21  sales  
0     6910.722989           97           10  4.593802e+06  6.910723e+04      1  
1    17599.075933           16           41  7.371874e+05  7.215621e+05      1  
2    26605.663926           52           54  1.757290e+06  1.436706e+06      1  
3    46273.559582            4          100  7.042010e+04  4.627356e+06      0  
4    43679.828556           57           18  1.350478e+06  7.862369e+05      1  
..            ...          ...          ...           ...           ...    ...  
995  18428.665422           55           41  1.904023e+06  7.555753e+05      1  
996   1450.477901           76           12  5.314393e+05  1.740573e+04      1  
997  15208.675539           87           15  1.966699e+06  2.281301e+05      1  
998   5447.333571           81           20  1.333855e+06  1.089467e+05      1  
999  48224.565049           80           31  2.031984e+06  1.494962e+06      1  

[1000 rows x 13 columns]

In [ ]:
1.지역에 따른 구매금액비교 >>>> 부유한 지역 확인1,2,3,4
2.나이(20대 30대, 40대, 50대)   (10살 미만은 잘라냄)와 성별로 구매금액 비교 >>> 가장 구매력 좋은 연령대와 성별 30대 여성 40대 여성, 가장 구매력이 낮은 60대 이상 남자
3.21년도와  매출하락과, 고가제품 구매율상승  >>경제상황 분석 빈익빈 부익부
4.제품 가격애 따른 
5.고가제품 구매 연령 2,30대 젊은층 큼, 저가제품(식료품) 주부 구매

In [38]:
# 지역에 따른 구매금액 비교
#20년 21년 구매금액의 합계를 정렬해서 금액이 적은구간 부터 지역값을 100개씩 차례대로 대입함
df['amount_tt'] = df.amount_20 + df.amount_21 # 20년 21년 구매금액의 합계
df.amount_tt = np.sort(df.amount_tt)
for i in range(10):
    df.region[i*100:(i+1)*100] = 10-i
df


cusno  gender  age  region  product_20  product_21      price_20  \
0      827       1   23      10          20          20  47358.786699   
1      504       0   59      10          20          10  46074.212780   
2      399       1   26      10          10          30  33794.033492   
3      748       1   19      10          20          20  17605.025554   
4      226       1   58      10          20          30  23692.594117   
..     ...     ...  ...     ...         ...         ...           ...   
995    978       0   52       1          20          30  34618.604804   
996    578       1   59       1          30          20   6992.622037   
997    541       0   30       1          20          10  22605.730592   
998    616       1   29       1          10          10  16467.342294   
999    380       0   75       1          10          20  25399.795566   

         price_21  quantity_20  quantity_21     amount_20     amount_21  \
0     6910.722989           97           10  4.593802e+06  6.910723e+04   
1    17599.075933           16           41  7.371874e+05  7.215621e+05   
2    26605.663926           52           54  1.757290e+06  1.436706e+06   
3    46273.559582            4          100  7.042010e+04  4.627356e+06   
4    43679.828556           57           18  1.350478e+06  7.862369e+05   
..            ...          ...          ...           ...           ...   
995  18428.665422           55           41  1.904023e+06  7.555753e+05   
996   1450.477901           76           12  5.314393e+05  1.740573e+04   
997  15208.675539           87           15  1.966699e+06  2.281301e+05   
998   5447.333571           81           20  1.333855e+06  1.089467e+05   
999  48224.565049           80           31  2.031984e+06  1.494962e+06   

     sales     amount_tt  
0        1  5.110239e+04  
1        1  1.114388e+05  
2        1  1.407855e+05  
3        0  1.454403e+05  
4        1  1.653479e+05  
..     ...           ...  
995      1  7.322537e+06  
996      1  7.433945e+06  
997      1  7.633962e+06  
998      1  7.743084e+06  
999      1  7.767636e+06  

[1000 rows x 14 columns]