# Q1. 남녀 파트너 정해주기 프로그램(zip) 
같은 수의 남녀 모임에서 파트너를 랜덤하게 정해주는 프로그램을 만들어 보세요

male = ['철수','갑돌','로미오','이몽룡','온돌']

female = ['미미','갑순','줄리엣','성춘향','평강']
zip 함수 사용


In [1]:
import random
male = ['철수','갑돌','로미오','이몽룡','온돌']
female = ['미미','갑순','줄리엣','성춘향','평강']
random.shuffle(male)
random.shuffle(female)
couples = zip(male, female)
for i, couple in enumerate(couples):
    print(f'커플{i+1}:{couple[0]},{couple[1]}')

커플1:이몽룡,미미
커플2:로미오,줄리엣
커플3:갑돌,성춘향
커플4:온돌,평강
커플5:철수,갑순


# Q2. 사용자가 입력한 횟수만큼 로또 번호를 출력하는 프로그램을 작성하세요.
중복불가 45개 중에 6개

In [2]:
a = int(input('자동 몇 줄 추출할거임?(숫자입력)'))
for i in range(a):
    print(random.sample(range(1,46), 6))

자동 몇 줄 추출할거임?(숫자입력)1
[18, 6, 7, 9, 22, 41]


## 도전  
발표자를 원하는 수 만큼 랜덤하게 출력하는 프로그램을 작성하세요.

In [3]:
cakd7 = ['박영권','김현지','김덕현','변서연','한지웅','양주희','이호원','정지은','이정현A','이상윤','이명진','조승현','강유한','김영선','최애림','김민섭','박혜린','이정현B','윤정준','김진형','정승기','진청아','신창훈','김병석','박세희'] 
len(cakd7)

25

In [4]:
a = int(input('발표자 몇 명 뽑을까요?'))
b = random.sample(cakd7,a)
for i in range(a):
    print(f"{i+1}번 문제 : {b[i]}")

발표자 몇 명 뽑을까요?1
1번 문제 : 한지웅


# Q3. 입력받은 문자열의 각 문자를 그 다음 문자로 변경하여 출력하세요 abc ->bca

In [5]:
s = input("문자를 입력하세요")
s[1:] + s[0]

문자를 입력하세요123


'231'

In [6]:
#abc -> cab
text = input("문장을 입력하세요")
ret = ''
for i in range(len(text)):
    if i != len(text) :
        ret += text[i-1]
    else:
        ret += text[0]
print(ret)

문장을 입력하세요123
312


# Q4. url에서 호스트 도메인을 추출하여 출력하세요.
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'


In [7]:
import re
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'
a = re.compile(r"http://([\w.]+)")
b = a.findall(url) #findal은 리스트화 
b[0]

'news.naver.com'

In [8]:
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'

tmp = url.split('/')
tmp[2]

'news.naver.com'

# Q5. url에서 쿼리문을 추출하여 출력하세요

In [9]:
# url에서 '?'뒤에 표시되는 문자열을 쿼리 문자열이라고 하며 변수=값 사이 &로 
# 구분되어 나열된다.
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'


In [10]:
url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'
tmp = url.split('&')
tmp.remove(tmp[0])
tmp

['mid=shm', 'sid1=105', 'oid=028', 'aid=0002334601']

# Q6. 텍스트 파일(mydata.txt)을 읽고  파일의 내용에서 나타나는 문자들에 대해 자주 나타나는 문자들을 아래와 같이 순서대로 출력하세요.
- \[ \] -> [177]회 나타남
- [e] -> [97]회 나타남
- [t] -> [85]회 나타남
   
   
   문장.count(문자)


In [11]:
import re
with open('mydata.txt',"r") as f:
    lines = f.readlines()
ci = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',' ',"'",'!']

In [12]:
lines[1]

"we've got to live with on our way\n"

In [13]:

import operator
di={}
sum=0
for j in ci:
    for i in range(0, len(lines)):
        sum += lines[i].count(j)
        di[j]=sum
    sum=0          
# dii = sorted(di.values(), reverse=True)
# dii
dii = sorted(di.items(), key=operator.itemgetter(1), reverse=True)
dii

[(' ', 177),
 ('e', 97),
 ('t', 85),
 ('a', 78),
 ('o', 73),
 ('n', 60),
 ('s', 60),
 ('r', 54),
 ('i', 50),
 ('h', 48),
 ('l', 34),
 ('u', 27),
 ('d', 24),
 ('c', 23),
 ('m', 20),
 ('w', 20),
 ('f', 17),
 ('p', 15),
 ('y', 15),
 ('b', 13),
 ('g', 11),
 ('v', 9),
 ("'", 8),
 ('k', 7),
 ('!', 2),
 ('j', 0),
 ('q', 0),
 ('x', 0),
 ('z', 0)]

In [14]:
def getTextFreq(filename):
    with open('mydata.txt',"r") as f:
        text = f.read()
        fa = {}
        for c in text:
            if c in fa:
                fa[c] += 1
            else:
                fa[c] = 1
    return fa
ret = getTextFreq('data/mydata.txt')
ret = sorted(ret.items(),key=lambda x:x[1], reverse=True)
print(ret)
for c, freq in ret:
    if c =='\n':
        continue
    print('[%c] - > [%d]회 나타남' %(c,freq))


[(' ', 177), ('e', 97), ('t', 85), ('a', 78), ('o', 73), ('n', 60), ('s', 60), ('r', 54), ('i', 50), ('h', 48), ('\n', 43), ('l', 34), ('u', 27), ('d', 24), ('c', 23), ('w', 20), ('m', 20), ('f', 17), ('y', 15), ('p', 15), ('b', 13), ('g', 11), ('v', 9), ("'", 8), ('k', 7), ('!', 2)]
[ ] - > [177]회 나타남
[e] - > [97]회 나타남
[t] - > [85]회 나타남
[a] - > [78]회 나타남
[o] - > [73]회 나타남
[n] - > [60]회 나타남
[s] - > [60]회 나타남
[r] - > [54]회 나타남
[i] - > [50]회 나타남
[h] - > [48]회 나타남
[l] - > [34]회 나타남
[u] - > [27]회 나타남
[d] - > [24]회 나타남
[c] - > [23]회 나타남
[w] - > [20]회 나타남
[m] - > [20]회 나타남
[f] - > [17]회 나타남
[y] - > [15]회 나타남
[p] - > [15]회 나타남
[b] - > [13]회 나타남
[g] - > [11]회 나타남
[v] - > [9]회 나타남
['] - > [8]회 나타남
[k] - > [7]회 나타남
[!] - > [2]회 나타남


# Q7. 두개의 수를 입력한 후 두개의 수에 대한 사칙연산을 수행하세요.(0을 입력한 경우 다시 입력하도록 조치)

In [15]:
# class를 만들어서 작성하세요
class Cal4:
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def add(self):
            return self.a+self.b
    def sub(self):
            return self.a-self.b
    def mul(self):
            return self.a*self.b
    def div(self):
            return self.a/self.b
while True:
    a = int(input("첫번째 숫자"))
    b = int(input("두번째 숫자"))
    if b == 0:
        print("0이 아닌 숫자를 입력하세요")
        continue
    else:
        cals = Cal4(a,b)
        print(f"덧셈 : {cals.add()}")
        print(f"뺄셈 : {cals.sub()}")
        print(f"곱셈 : {cals.mul()}")
        print(f"나눗셈 : {cals.div()}")
        break
                    


첫번째 숫자1
두번째 숫자1
덧셈 : 2
뺄셈 : 0
곱셈 : 1
나눗셈 : 1.0


# Q8. Order 클래스를 상속받아 ExtraOrder 클래스에서 메소드 오버라이딩하여 출력가격에 원이 추가되도록 출력하세요


In [16]:
class Order: 
    def __init__(self, name): 
        self.customer = 0 
        self.name = name 
    def order(self, price): 
        self.customer += price 
        return self.customer

order = Order('고갱')

class ExtraOrder(Order):
    def __init__(self, name):
        super().__init__(name)
    def order(self, price):
        super().order(price)
        print(f'{self.name}님의 주문금액은 {self.customer}원 입니다')
order = ExtraOrder('고갱')
order.order(1000)
    

고갱님의 주문금액은 1000원 입니다


#  Q9. 업무미팅이 2시임을 알려주는 자동 이메일 클래스 AutoEmail을 작성하여 아래와 같이 출력하세요 (미팅이 진행되는 2시에는 업무미팅이 진행중이라는 문구를 추가)

안녕하세요 고갱님. 업무미팅은 2시입니다.

In [17]:
import time
class AutoEmail:
    def __init__(self, name, t):
        self.name = name
        self.t = t
    def alarm(self):
        if time.localtime().tm_hour==self.t:
            print(f"{self.name}님, 업무미팅이 진행중 입니다.")
        else:
            print(f"안녕하세요 {self.name}님, 업무미팅은 {self.t}시 입니다.")
AE= AutoEmail("고갱",9)
AE.alarm()        

안녕하세요 고갱님, 업무미팅은 9시 입니다.


0719

# Q10. 정규표현식을 사용하여 text에서 전화번호만 출력하세요.
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [18]:
import re
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a= re.compile(r'\d+-\d+-\d+')
a.findall(text)
# 서치로 하면 된다는디?

['032-232-3245']

In [19]:
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a= re.compile(r'\d+-\d+-\d+')
a.search(text)

<re.Match object; span=(10, 22), match='032-232-3245'>

# Q11. 정규표현식을 사용하여 text에서 에러가 들어간 부분만 포함하는 리스트를 출력하세요
text = "에러 1122, 레퍼런스 오류, 에러 1033, 아규머먼트 오류, 에러 xxx"

In [20]:
text = "에러 1122, 레퍼런스 오류, 에러 1033, 아규머먼트 오류, 에러 xxx"
a = re.compile(r"\w{2} [0-9a-z]+")   #\s = 띄어쓰기    \D 숫자 아닌 모든것 문자 기호등..  \d 숫자만  
b = a.findall(text)
b

['에러 1122', '에러 1033', '에러 xxx']

In [21]:
c = re.compile(r"에러 \w+")
d = c.findall(text)
d

['에러 1122', '에러 1033', '에러 xxx']

# Q12. 정규포현식을 사용하여 text에서 지역코드만 출력하세요
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [22]:
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a = re.compile(r"(\d+)-(\d+)-(\d+)")
b = a.findall(text)
b[0][0]

'032'

In [23]:
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a = re.compile(r"(\d+)-(\d+)-(\d+)")
b = a.search(text)
b.group(1)

'032'

# Q13. 정규표현식을 사용하여 text에서 지역코드를 제외한 번호만 출력하세요.
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [24]:
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a = re.compile(r"(\d+)-(\d+[-]\d+)")
b = a.findall(text)
b[0][1]

'232-3245'

In [25]:
text = "문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."
a = re.compile(r"(\d+)-(\d+[-]\d+)")
b = a.search(text)
b.group(2)

'232-3245'

# Q14.'abcdefghij' 에 대하여 중첩을 적용한 서브그룹 5개로 컴파일하여 group()함수를 이용하여 'abcdefghi'와 e'를 출력하세요


In [26]:
text = 'abcdefghij'
# a = "((a(b(cd(e)f)gh)i)j)"
a = re.compile(r"((\w(\w(\w{2}(\w)\w)\w{2})\w)\w)")
b = a.search(text)
b
# print(b[0][1], b[0][4])
print(b.group(2), b.group(5))

abcdefghi e


In [27]:
a = re.compile(r"((a(b(cd(e)f)gh)i)j)")
b = a.search(text)
# print(b.group(2), b.group(5))
b.group(2,5)

('abcdefghi', 'e')

# Q15. 위 문제에서 모든 서브 그룹에 대한 문자열을 포함하는 튜플을 출력하세요. finditer? search? match? groups면 됨

In [28]:
b.groups()

('abcdefghij', 'abcdefghi', 'bcdefgh', 'cdef', 'e')

0720

# Q16. 이름으로 그룹을 참조하여 'Lots of punctuation' 에서 Lots를 출력하세요.
그룹에 이름붙여 하는 법?

In [29]:
text = 'Lots of punctuation'
a = re.compile(r"(?P<ff>\w+) \w+ \w+")
b = a.match(text)
b.group('ff')

'Lots'

# Q17. 'Paris is very very beautiful.'에서 'very very'를 출력하세요.


In [30]:
text = 'Paris is very very beautiful.'
a = re.compile(r"\w+ \w+ (\w+ \w+) \w+.")
b = a.match(text)
b.group(1)

'very very'

# Q18. 정규표현식을 작성하여 아래와 같이 출력하세요.
['1 apple', '5 oranges', '3 boys', '4 girls', '10 army', '11 mr']

In [2]:
import re
li = '1 apple, 5 oranges, 3 boys, 4 girls; 10 army| 11 mr'
regex = re.compile(r"\d+ \w+")
lii = regex.findall(li)
print(lii)

['1 apple', '5 oranges', '3 boys', '4 girls', '10 army', '11 mr']


# Q19. text에서 'H,h'만 출력하세요.

In [3]:
text = 'Hello my friend! Life is short you need Python!'
a = re.compile(r"h", re.I)   #IGNORECASE : 대소문자를 구분하지 않음
b = a.findall(text)
b

['H', 'h', 'h']

In [4]:
text = 'Hello my friend! Life is short you need Python!'
a = re.compile(r"[Hh]")
b = a.findall(text)
b

['H', 'h', 'h']

# Q20. text에서 'H,h'가 아닌 것 모두를 출력하세요.

In [6]:
text = 'Hello my friend! Life is short you need Python!'
a = re.compile(r"[^Hh]")
b = a.findall(text)
print(b)

['e', 'l', 'l', 'o', ' ', 'm', 'y', ' ', 'f', 'r', 'i', 'e', 'n', 'd', '!', ' ', 'L', 'i', 'f', 'e', ' ', 'i', 's', ' ', 's', 'o', 'r', 't', ' ', 'y', 'o', 'u', ' ', 'n', 'e', 'e', 'd', ' ', 'P', 'y', 't', 'o', 'n', '!']


0721

# Q21.  'we are going home'에서 home만 출력하세요.


In [8]:
text = 'we are going home'
a = text.split(" ")
a[3]

'home'

# Q22. '199305, 1923A, a93247'에서 '199305'만 출력하세요.


In [10]:
text = '199305, 1923A, a93247'
a = text.split(",")
a[0]

'199305'

# Q23. '12345abc'에서 'abc'만 출력하세요.

In [3]:
import re
text = '12345abc'
text[-3:]

'abc'

In [7]:
a = re.search(r"\D+", text)
a.group()

'abc'

In [13]:
re.sub(r'\D+',"",text)

'12345'

# Q. '12345abc'에서 'a'만 출력하세요.


In [15]:
text = '12345abc'
text[-3]

'a'

In [16]:
a = re.search(r"\D", text)
a.group()

'a'

# Q. 'abc12345Abc'에서 'A'만 출력하세요.


In [17]:
text = 'abc12345Abc'
text[-3]

'A'

In [18]:
a = re.search(r"[A-Z]+", text)
a.group()

'A'

0722

# Q. 'Banker'에서 'anker', 'banker123'에서 'banker'를 출력하세요


In [6]:
import re
text = 'Banker'
a = re.search(r"[a-z]+", text)
print(a.group())
a = re.search(r"[^A-Z]+", text)
print(a.group())
text = 'banker123'
a = re.search(r"[a-z]+", text)
print(a.group())
a = re.search(r"[\D]+", text)
print(a.group())


anker
anker
banker
banker


# Q. 'KOREA 대한민국'에서 '대'만 출력하세요.


In [3]:
text = 'KOREA 대한민국'
a = re.search(r"[가-힣]", text)
a.group()

'대'

# Q. text에서 'aaaaBBBcccDDDeee'을 모두 출력하세요.
text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'


In [6]:
text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'
a = re.search(r"[a]{4}\w{12}", text)
a.group()

'aaaaBBBcccDDDeee'

# Q. 아래의 경우에서 \<html>만 출력하세요


In [8]:
text = '<html><head><title>Title</title></head><body></body></html>'

pattern = re.compile('<.*?>')
#탐욕 논 그리디 써보셈 *?는 모든 것중에 가장 짧은것
# <p>.*</p> 는 <p>asd</p>asd<p>asd</p> 이런식이면 asdasdasd가 출력됨
# <p>.*?</p> 는 <p>asd</p>asd<p>asd</p> 에서 맨앞 asd 만 출력

print(len(text))
p = pattern.search(text)
p.group()


59


'<html>'

# Q. '1234a1234'에서  '1', '2', '3', '4'를 모두 출력하세요.


In [7]:
text = '1234a1234'

a = re.findall(r"\d", text)  # 리스트
# set(a)
a

['1', '2', '3', '4', '1', '2', '3', '4']

0725

# Q. text에서 전체문장 모두 출력하세요.


In [1]:
import re
text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"
# regex = re.compile(r'[a-z?\n\s]+')
regex = re.compile('\D+')
mo = regex.search(text)
print(mo.group())


what are you doing?
it is going to be late for school
we need to hurry up


In [2]:
regex = re.compile('.*', re.DOTALL)  # * 는 \n 빼고 다 
mo = regex.search(text)
print(mo.group())


what are you doing?
it is going to be late for school
we need to hurry up


# Q. text에서 대소문자 구분없이 전체문장 모두 출력하세요


In [23]:
text = 'Friend fRiend friEnd FRIEND'
a = re.search('[\w ]+', text)
a.group()

'Friend fRiend friEnd FRIEND'

In [88]:
text = 'Friend fRiend friEnd FRIEND'
a = re.findall('\w', text)
for i in a:
    print(i, end=' ')

F r i e n d f R i e n d f r i E n d F R I E N D 

In [89]:
text = 'Friend fRiend friEnd FRIEND'
a = re.findall('\w+', text)
for i in a:
    print(i, end=' ')

Friend fRiend friEnd FRIEND 

In [4]:
text = 'Friend fRiend friEnd FRIEND'
regex = re.compile('[a-z]+',re.I)
mo = regex.findall(text)
for i in mo:
    print(i)


Friend
fRiend
friEnd
FRIEND


# Q. 1609160537.371015을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.


In [25]:
import time
from datetime import datetime
a = 1609160537.371015  # 타임스탬프

f = '%a %b %d %H:%M:%S %Y' # 포맷

        
b = datetime.fromtimestamp(a).strftime(f)  # 타임스탬프a를 f 포맷 스트링으로 변환
b                                        



'Mon Dec 28 22:02:17 2020'

In [7]:
c = datetime.fromtimestamp(a).strftime('%c')
c

'Mon Dec 28 22:02:17 2020'

In [8]:
timestring = time.ctime(a)
timestring

'Mon Dec 28 22:02:17 2020'

ctime() 함수는 주어진 timestamp를 현지 시간대 기준으로 소위 미국에서 흔히 사용되는 요 월 일 시:분:초 년 포멧으로 변환해줍니다. 그냥 간단하게 timestamp가 나타내는 날짜와 시간을 확인해보는 용도로 쓰기에 좋습니다.


In [17]:
a = 1609160537.371015
b = time.strftime(f, time.localtime(a)) # 타임스탬프a를 f 포맷 스트링으로 변환
b

'Mon Dec 28 22:02:17 2020'

# Q. 현재 날짜와 시간을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.


In [18]:
a = time.localtime() # 현재 시각을 struct_time으로
f = '%a %b %d %H:%M:%S %Y'
b = time.strftime(f, a) # struct_time을 str로
print(b)



Tue Jul 26 00:51:41 2022


In [19]:
a

time.struct_time(tm_year=2022, tm_mon=7, tm_mday=26, tm_hour=0, tm_min=51, tm_sec=41, tm_wday=1, tm_yday=207, tm_isdst=0)

0726

# Q. 현재 시간을 년-월-일 시:분:초로 출력하세요.


In [1]:
import time
t = time.localtime()  # 스트럭쳐 타임
f = '%Y-%m-%d %H:%M:%S'
time.strftime(f, t)

'2022-07-27 08:41:48'

# Q. 현재 시간을 time.time을 불러와서 년-월-일 시:분:초로 출력하세요.


In [2]:
from datetime import datetime
t = time.time()    # 타임 스탬프
f = '%Y-%m-%d %H:%M:%S'
d = datetime.fromtimestamp(t).strftime(f)
d

'2022-07-27 08:41:48'

# Q. 올해 경과된 날짜수 계산하세요


In [26]:

t = time.localtime()
t.tm_yday
print(f"오늘은 2022년 01월 01일 이후 {t.tm_yday}일차가 되는 날입니다.")

오늘은 2022년 01월 01일 이후 208일차가 되는 날입니다.


In [28]:
# 두 날짜간의 일수 구하기
from datetime import datetime
since_timestamp = datetime.strptime('20220101','%Y%m%d')
t = time.time()
until_timestamp = datetime.fromtimestamp(t)

result = until_timestamp - since_timestamp
print(f"오늘은 2022년 01월 01일 이후 {result.days}일이 되는 날입니다.")

오늘은 2022년 01월 01일 이후 207일이 되는 날입니다.


# Q. 현재 요일을 "2021-6-26 오늘은 토요일입니다."와 같은 형식으로 출력하세요.


In [6]:
t = datetime.today()
d = datetime.strftime(t, '%Y-%m-%d')
u = datetime.strftime(t, '%u' )
w = t.weekday()
dic = {0:'월',1:'화',2:'수',3:'목',4:'금',5:'토',6:'일'}

print(f'{d} 오늘은 {dic[w]}요일입니다.')

2022-07-27 오늘은 수요일입니다.


In [18]:
import datetime
def get_yoil(y, m, d):
    days = ['월','화','수','목','금','토','일']
    return days[datetime.date(y, m, d).weekday()]
get_yoil(2022,7,27)

'수'

In [31]:
t = datetime.datetime.today()
d = datetime.datetime.strftime(t, '%Y, %m, %d')
# get_yoil(d)
d.

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

# Q. 1에서 백만까지 더하는데 걸리는 프로그램 실행 시간을 밀리초(ms) 단위로 구하세요.


In [8]:
# 구글링
start_time = time.perf_counter()

s = 0
for i in range(1,1000001):
    s += i

end_time = time.perf_counter()
print(f"걸린 시간 : {int(round((end_time - start_time) * 1000))}ms")

걸린 시간 : 141ms


In [9]:
s = 0
%time for i in range(1,1000001): s += i 
    
# 소수점 처리 {함수? :.숫자f}

CPU times: total: 141 ms
Wall time: 153 ms


0727

# Q. 아래 코드를 보완하여 발생 가능한 모든 예외(정수, 인덱스, 미리 파악하지 못한 예외)를 처리한 후 마지막에  '모든 예외처리 완료'를 출력하세요.


In [12]:
## Q. 
list_num = [52,273,32,72,100]
try:
    num_input = int(input('정수 입력> '))
    print(f'{num_input}번째 요소: {list_num[num_input-1]}')
except ValueError:  # ValueError 정수에러 , IndexError 인덱스에러, ExceptError 예외적에러
    print("정수에러")
except IndexError:
    print('인덱스에러')
except IndexError:
    print('인덱스에러')
finally:
    print("예외처리완료")
    

정수 입력> 6
인덱스에러
예외처리완료


# Q. 기본가격 1000원인 2개의 상품에 대하여 임의의 추가 가격을 입력시 가격 조정한 결과를 반환하는 Price 클래스를 생성 후 객체를 만들어 price1, price2를 수행하세요. 
- price1 : 기본가격 + 추가가격
- price2 : (기본가격 + 추가가격) * 90%


In [6]:
class Price :
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def price1(self, c):
        self.c = c
        return(self.a+self.c, self.b+self.c)
    def price2(self, d):
        self.d = d
        return((self.a+self.d)*0.9, (self.b+self.d)*0.9)
    
price = Price(1000, 1000)
x = price.price1(500)
print(f"price1 결과 : {x}")
y = price.price2(500)
print(f"price2 결과 : {y}")

price1 결과 : (1500, 1500)
price2 결과 : (1350.0, 1350.0)


# Q. strings를 문자의 크기 순서로 내림차순 정렬하세요


In [10]:
strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']
strings.sort(key=len, reverse=True)
strings

['ababa', 'aaaa', 'bar', 'ca', 'a']

# Q. strings를 다양한 문자가 포함된 순서로 정렬하세요


In [71]:
# Q.
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']
strings.sort(key = lambda x:len(set(x)), reverse=True)
strings


['card', 'bar', 'foo', 'abab', 'aaaa']

# Q. 'abcde' 를 'edcba'로 바꾸어 출력하세요.(5가지 방법)
reverse, ascending, 인덱싱, 슬라이싱


In [14]:
text = 'abcde'    # sort 객체지향  sorted는 아닌가?  

#1
print(text[::-1])
#2
li=[]
for i in range(0,len(text)):
    li.append(text[4-i])
li = ''.join(li)
print(li)
#3
li = sorted(text, reverse=True)  # 새 리스트를 만들어서 ascnding 정렬함
li = ''.join(li)
print(li)
#4
li = list(text)
li.sort(reverse=True)   # 스트링은 정렬 안됨 그래서 쪼개줌
li = ''.join(li)
print(li)
#5
print(text.split()[0][::-1])   # 스플릿이 스트링을 하나의 리스트화함

edcba
edcba
edcba
edcba
edcba


0728

# Q. numbers 내부에 들어 있는 숫자가 몇 번 등장하는지를 출력하는 코드를 작성하세요.
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]


In [45]:
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]
for i in range(10):
    if i in numbers:
        print(f'{i} 는 {numbers.count(i)}')
    else:
        pass

2 는 2
3 는 4
4 는 2
5 는 2
6 는 2
7 는 2
8 는 2
9 는 2


# Q. 코딩을 한줄로 작성해서 동일한 결과를 출력하세요


In [15]:
# Q.
list = []
for i in range(0,20,2):
    list.append(i*i)
print(list)


[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


In [65]:
[(i*i) for i in range(0,20,2)]


[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]

# Q. 반복문으로 팩토리얼을 구하는 사용자 함수를 작성하고 5!, 10!를 구하세요.


In [3]:
def fac(a):
    x=1
    for i in range(1, a+1):
        x *=i
    return x
print(fac(5))
print(fac(10))

120
3628800


# Q. 재귀란 '자기자신을 호출하는 것'을 의미한다. 재귀함수를 이용해서 팩토리얼을 구하는 사용자 함수를 작성하고 1!, 5!, 10!를 구하세요.
factorial(n) = n * factorial(n-1) (n >= 1)


In [9]:
def fac(a):
    if a==0 | a ==1 :
        return 1
    else:
        return a*fac(a-1)
print(fac(5))
print(fac(10))

120
3628800


# Q. list a의 모든 원소를 실수형으로 바꾸어 출력하세요


In [34]:
a = [1,2,3,4,5]
li = []
for i in range(5):
    li.append(float(a[i]))
li

[1.0, 2.0, 3.0, 4.0, 5.0]

In [11]:
a = [1,2,3,4,5]
# list(map(lambda x:float(x),a))
a = list(map(float,a))
a

[1.0, 2.0, 3.0, 4.0, 5.0]

0729

# Q 31 문자열 리스트 states를 정형화하여 아래와 같이 출력하세요.
```
Q. 
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
[출력]
['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']
```

In [3]:
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
import re
li =[]
for i in states:
    i = re.sub('[!?#]','', i)
    i = i.title().strip()
    li.append(i)
li

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

# Q51. 게시물의 총 건수와 한 페이지에 보여 줄 게시물 수를 입력시 총 페이지 수를 출력하는 프로그램
사용자함수 사용용용

In [4]:
def show(a,b):
    if a%b == 0:
        print(f'총 페이지 수 : {a//b}')
    else:
        print(f'총 페이지 수 : {a//b +1}')
        
a = int(input("총 게시물 수"))
b = int(input("한 페이지 당 게시물 수"))
show(a,b)    

총 게시물 수100
한 페이지 당 게시물 수5
총 페이지 수 : 20


# Q52. 랜덤하게 1000명의 이름, 키와 몸무게 만들어 저장한 후 다시 불러내어 다음과 같이 출력하세요.

- 이름 :라바
- 몸무게: 80
- 키: 146
- BMI: 37.53049352598987
- 결과: 과체중


In [ ]:
몸무게(kg)를 키의 제곱(m)으로 나눈 값
18.5 이하면 저체중 ／ 18.5 ~ 22.9 사이면 정상 ／ 23.0 ~ 24.9 사이면 과체중 ／ 25.0 이상부터는 비만으로 판정

In [1]:
import random
import pandas as pd
import numpy as np

In [7]:
name=[]
for i in range(1000):
    fn = random.choice('김이박조강장윤정최')
    mn = random.choice('민상윤유우영정철영')
    ln = random.choice('지윤석한원호석수희')
    name.append(fn+mn+ln)
name = pd.Series(name)


df = pd.DataFrame(columns={'name','weight','height','BMI','conclusion'})
df['name']=name
df['weight'] = np.random.randint(40,120, size=1000)
df['height'] = np.random.randint(140,200, size=1000)   # 노멀로 정규분포 만들지 그랬니 random.normal(평균,표준편차,개수)
df['BMI'] = df['weight']/(df['height']*0.01)**2

def f(x):
    if x<18.5:
        return '저체중'
    elif x<22.9:
        return '정상'
    elif x<24.9:
        return '과체중'
    else:
        return '비만'
df['conclusion'] = df['BMI'].apply(lambda x: f(x))
df

name  weight conclusion  height        BMI
0    정유한      92         비만     184  27.173913
1    최영지      44        저체중     167  15.776830
2    조정윤      81         정상     198  20.661157
3    이윤호     102         비만     177  32.557694
4    김유원     104         비만     168  36.848073
..   ...     ...        ...     ...        ...
995  윤윤원      72         비만     164  26.769780
996  최우희     110         비만     189  30.794211
997  조영석     112         비만     149  50.448178
998  장철호      72         비만     168  25.510204
999  장유석      58        저체중     193  15.570888

[1000 rows x 5 columns]

In [9]:
df = df[['name','weight','height','BMI','conclusion']]

In [10]:
df.iloc[0]

name                정유한
weight               92
height              184
BMI           27.173913
conclusion           비만
Name: 0, dtype: object

0801

#  Q. 입력한 숫자를 천 단위로 구분하여 출력하세요. 
f스트링

In [2]:
a=int(input("정수 입력"))
print(f'{a:,}')


정수 입력1000000
1,000,000


# Q. 카운터에서 거스름돈으로 사용할 500원 10원 50원 10원 짜리 동전이 무한히 존재한다고 가정한다. 손님에게 거슬러줘야할 돈이 N원일 때 거슬러 줘야할 동전의 최솟 개수를 구하세요. 단, 거슬러줘야할 돈 N은 항상 10의 배수이다. N=2750원

In [11]:
def f(N):
    i=0
    while True:
        if N>=500:
            N -=500
            i +=1
        elif N>=100:
            N -=100
            i +=1
        elif N>=50:
            N -=50
            i +=1
        elif N>=10:
            N -=10
            i +=1
        else:
            break 
    print(i)

In [12]:
f(2750)

8


In [19]:
def f(N):
    li=[0,0,0,0]
    while True:
        if N>=500:
            N -=500
            li[0] +=1
        elif N>=100:
            N -=100
            li[1] +=1
        elif N>=50:
            N -=50
            li[2] +=1
        elif N>=10:
            N -=10
            li[3] +=1
        else:
            break 
    print(f'500원 {li[0]}\n100원 {li[1]}\n50원 {li[2]}\n10원 {li[3]}\n최소 개수 {li[0]+li[1]+li[2]+li[3]}')

In [20]:
f(2750)

500원 5
100원 2
50원 1
10원 0
최소 개수 8


In [3]:
n = 2750
count = 0

# 큰 단위의 화폐부터 차례대로 확인하기
coin_types = [500, 100, 50, 10]

for coin in coin_types:
    count += n // coin # 해당 화폐로 거슬러 줄 수 있는 동전의 개수 세기
    n %= coin # 나머지를 n에

print(count)


8


0802

# Q. ./mydata.txt 파일에 있는 단어 개수를 출력하세요.


In [2]:
import re

In [25]:
with open('./mydata.txt','r')as f:
    lines = f.readlines()
lines

['a lot of things occur each day\n',
 "we've got to live with on our way\n",
 "there's so much misery on the screen\n",
 'with commercials in between\n',
 '\n',
 "and the russians won't be so late\n",
 "uncle sam don't want to wait\n",
 "no matter if you're black or white\n",
 'you never ever had a right\n',
 '\n',
 'and look up to the eternal skies\n',
 'see warfare even there\n',
 'what once has been a paradise\n',
 'now destruction and despair\n',
 '\n',
 'in other worlds the children die\n',
 'lacking food ill from a fly\n',
 'oppressed by troops to tame their land\n',
 "it's all the same again\n",
 '\n',
 'if any man is free on earth\n',
 'then tormentors steal his birth\n',
 'they slam gun butts in his face\n',
 'and leave his woman choked in mace\n',
 '\n',
 'so stand up for our human rights\n',
 'push back this pest of hate\n',
 'raise you voice pass on the light\n',
 "unite! it's not too late\n",
 '\n',
 'how many tears flow away\n',
 'to become a sea of fears\n',
 'how many h

In [8]:
with open('./mydata.txt','r')as f:
    data = f.read()
data

"a lot of things occur each day\nwe've got to live with on our way\nthere's so much misery on the screen\nwith commercials in between\n\nand the russians won't be so late\nuncle sam don't want to wait\nno matter if you're black or white\nyou never ever had a right\n\nand look up to the eternal skies\nsee warfare even there\nwhat once has been a paradise\nnow destruction and despair\n\nin other worlds the children die\nlacking food ill from a fly\noppressed by troops to tame their land\nit's all the same again\n\nif any man is free on earth\nthen tormentors steal his birth\nthey slam gun butts in his face\nand leave his woman choked in mace\n\nso stand up for our human rights\npush back this pest of hate\nraise you voice pass on the light\nunite! it's not too late\n\nhow many tears flow away\nto become a sea of fears\nhow many hearts are torn apart\ntill another torment starts\n\nbut before the world\nturns into a sun\nall cruelty and violence\non earth will be dead and gone\n\nso stand

In [4]:
with open('./mydata.txt','r')as f:
    lines = f.readlines()
a=0
for line in lines:
    a+=len(re.findall('\w+',line))
a
# a = re.compile('\w+')
# b = a.findall(lines)
# len(b)

221

In [10]:
with open('./mydata.txt','r')as f:
    data = f.read()
    tmp = data.split()
    tmp = re.sub("'",' ', tmp)
    print(f'단어 수 : {len(tmp)}')


단어 수 : 213


# Q. 파일이름과 특정 단어을 인자로 입력하면 그 파일에 있는 특정 단어의 개수를 반환하는 사용자 함수를 이용하여 mydata 파일에서 how의 개수를 출력하세요.


In [13]:
def word(t,w):
    with open(f'./{t}','r')as f:
        lines = f.readlines()
    a=0
    for line in lines:
        a+=len(re.findall(f'{w}',line))
    print(a)


In [14]:
word('mydata.txt','how')

2


In [15]:
def word(t,w):
    with open(f'./{t}','r')as f:
        data = f.read()
        a = len(re.findall(f'{w}',data))
        print(a)

In [16]:
word('mydata.txt','how')

2


In [18]:
def countWord(filename, word):
    with open(filename, 'r') as f:
        text = f.read()
        text = text.lower()
        pos = text.find(word)
        count = 0
        while pos != -1: # 없을때 까지
            count += 1
            pos = text.find(word, pos+1)
    return count

filename = input('filename을 입력하세요: ')
word = input('filename에서 개수를 구할 단어를 입력하세요: ').lower()
ret = countWord(filename, word)
print(f'{word}의 개수: {ret}')


filename을 입력하세요: mydata.txt
filename에서 개수를 구할 단어를 입력하세요: How
how의 개수: 2


In [26]:
countWord('mydata.txt','how')

2

0803

# Q59.
문자열을 입력받아 같은 문자가 연속적으로 반복되는 경우에 그 반복 횟수를 표시해 문자열을 압축하여 표시하세요.
- 예) "aaabbcccccca" -> a3b2c6a1


In [19]:
text = input('문자입력')
s=1
li=[]
for i in range(0,len(text)):
    if i==0:
        li.append(text[i])
    else:
        if text[i]==text[i-1]:
            s += 1
        else:
            li.append(str(s))
            li.append(text[i])
            s = 1
li=''.join(li)
li

문자입력aaabbcccca


'a3b2c4a'

In [20]:
from itertools import groupby
text = 'aaabbcccca'
for x, y in groupby(text):
    print(x, list(y))

a ['a', 'a', 'a']
b ['b', 'b']
c ['c', 'c', 'c', 'c']
a ['a']


# Q60.
N개의 요소 이루어진 배열이 있을 때 주어진 수들을 M번 더하여 가장 큰 수를 만드는 프로그램을 작성하세요. 단 배열의 특정한 인덱스(번호)에 해당하는 수가 연속해서 K번을 초과하여 더해질 수 없는 것이 특징이다.
프로그램은 다음 조건을 만족하는 N, M, K를 공백으로 일차 입력하고 N개의 배열을 공백으로 이차 입력하면 결과물을 출력하는 방식으로 수행함.
- 2 <= N <= 1000
- 1 <= M <= 10000
- 1 <= K <= 10000


In [ ]:
공백으로 입력받음 input
n m k
ex) 5 8 3

n개의 요소 배열 입력 
m번 더하시오
입력된 배열중에 가장큰수를 k번 제한



In [29]:
import numpy as np
import pandas as pd

In [3]:
N, M, K = input("N M K 입력").split(sep=' ')

arr = input(f"1 2 3 4 같이 {N}개의 요소 배열 입력").split(sep=' ')

arr.sort(reverse=True)

N M K 입력5 20 10
1 2 3 4 같이 배열 입력3 4 5 6 7


In [197]:
s = 0
M = int(M)
K = int(K)
if M <= K:
    print(int(arr[0])*M)
else:        
    li=[]
    for i in range(0,M):
        if arr[i] in li:
            pass
        else:
            s += int(arr[i])*K
            M -= K
            li.append(arr[i])
            if M <= K:
                s += int(arr[i+1])*M
                break
    print(s)

170


In [194]:
9*10 + 8*10

170

In [ ]:
# N, M, K를 공백을 기준으로 구분하여 입력 받기
n, m, k = map(int, input().split())
# N개의 수를 공백을 기준으로 구분하여 입력 받기
data = list(map(int, input().split()))

data.sort() # 입력 받은 수들 정렬하기
first = data[n - 1] # 가장 큰 수
second = data[n - 2] # 두 번째로 큰 수

# 가장 큰 수가 더해지는 횟수 계산
count = int(m / (k + 1)) * k
count += m % (k + 1)

result = 0
result += (count) * first # 가장 큰 수 더하기
result += (m - count) * second # 두 번째로 큰 수 더하기

print(result) # 최종 답안 출력


# Q61. file1, 2의 파일 크기를 각각 구하세요.

- file1 = 'data/stockcode.txt'
- file2 = 'data/img_sample.jpg'


In [2]:
import os
fs = os.path.getsize(r'./data/stockcode.txt')
print(fs, 'byte')

16339 byte


In [3]:
import os
fs = os.path.getsize(r'./data/img_sample.jpg')
print(fs, 'byte')

170005 byte


# Q62.
stockcode.txt의 105바이트 위치에서 500바이트를 읽어 그 내용은 stock_part.txt에 저장 한 후 출력하세요.


In [10]:
os.stat('./data/stockcode.txt')

os.stat_result(st_mode=33206, st_ino=8444249301574661, st_dev=814822718, st_nlink=1, st_uid=0, st_gid=0, st_size=16339, st_atime=1659660009, st_mtime=1659660007, st_ctime=1659660007)

In [3]:
import os

In [4]:
spos = 105    # 파일을 읽는 최초의 위치로 파일의 처음에서 105바이트 떨어진 부분 
size = 500     # 읽을 데이터의 크기는 500바이트

f = open('./data/stockcode.txt', 'rb') #rb 읽을때 바이트로
h = open('./data/stock_part.txt', 'wb')  # wb 쓸때 바이트로

f.seek(spos)
data = f.read(size)
h.write(data)

h.close()
f.close()

In [5]:
os.stat('./data/stock_part.txt')

os.stat_result(st_mode=33206, st_ino=21110623253348451, st_dev=814822718, st_nlink=1, st_uid=0, st_gid=0, st_size=500, st_atime=1659917660, st_mtime=1659917660, st_ctime=1659877168)

In [6]:
os.stat('./data/stock_part.txt').st_size

500

# Q64. 어떠한 수 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행하려고 한다. 단 두번째 연산은 N이 K로 나누어 떨어질 때만 선택할 수 있다.  N과 K를 입력했을 때 N이 1이 될 때까지 1번 혹은 2번의 과정을 수행해야 하는 최소 횟수를 구하는 프로그램을 완성하세요.

1. N에서 1을 뺀다.
2. N을 K로 나눈다.


In [26]:
def f(N, K):
    num=0
    while True:
        if N>1:
            if N%K==0:
                N = N//K
                num +=1
            else:
                N -=1
                num +=1
        else:
            break
    print(num)
f(15,7)

3


# Q65. 아래와 같이 출력하는 코드를 작성하세요.
```
*
**
***
****
*****

```

In [1]:
for i in range(1,6):
    print('*'*i)

*
**
***
****
*****


# Q66. 아래와같이 출력하는 코드를 작성하세요
```
     *
    ***
   *****
  *******
 *********
  *******
   *****
    ***
     *

```

In [4]:
n = 10
for i in range(1,n):
    if i<n//2:
        print(((n//2)-i)*' '+'*'*(2*i-1))
    else:
        print((i-(n//2))*' '+'*'*((2*n-1)-(2*i)))

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


# Q67. Tree의 높이를 입력하면 해당하는 높이의 아래와 같은 Tree를 출력하는 프로그램을 작성하세요.
```
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
        ***
        ***
        ***

```

In [3]:
l = int(input("나무높이?"))
if l < 4:
    for i in range(0,l):
        print('*')
elif l < 6:
    for i in range(1,l):
        print((l-i)*' '+'*'*((2*i)-1))
    print((l-1)*' '+'*')
elif l < 9:
    for i in range(1,l-1):
        print((l-i)*' '+'*'*((2*i)-1))
    for i in range(0,2):
        print((l-1)*' '+'*')
elif l < 14:
    for i in range(1,l-2):
        print((l-i)*' '+'*'*((2*i)-1))
    for i in range(0,3):
        print((l-2)*' '+'***')
elif l <= 20:
    for i in range(1,l-3):
        print((l-i)*' '+'*'*((2*i)-1))
    for i in range(0,4):
        print((l-3)*' '+'*****')
else:
    print('이 나무는 20까지만 자람')

나무높이?18
                 *
                ***
               *****
              *******
             *********
            ***********
           *************
          ***************
         *****************
        *******************
       *********************
      ***********************
     *************************
    ***************************
               *****
               *****
               *****
               *****


# Q68. 구구단을 출력하는 프로그래을 출력하세요.

In [2]:
def gugu(x):
    for i in range(1,10):
        print(f"{x}x{i}={x*i}")
x = int(input("구구단 몇 단?"))
gugu(x)

구구단 몇 단?3
3x1=3
3x2=6
3x3=9
3x4=12
3x5=15
3x6=18
3x7=21
3x8=24
3x9=27


# Q69. 아래와 같이 입력하면 N X M 행렬 형태의 숫자 카드 중에서 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한 후 그 행에서 가장 숫자가 낮은 카드를 뽑아야 하는 규칙하에서 가장 높은 숫자가 쓰인 카드 한장의 숫자를 출력한는 프로그램을 작성하세요. 
- 첫번째 입력 : N X M 형열에 대하여 N(행), M(열)의 개수를 공백을 기준으로 입력(1<= N, M<=100)
- 두번째 입력 : 각 행의 숫자를 공백을 기준으로 입력. 단, 각 숫자는 1 이상 10000 이하의 자연수임.


각 행의 최소값들을 선정하고 그중 최대값을 뽑는문제였네 

In [1]:
import numpy as np
import pandas as pd

In [17]:
# while True:
#     N,M = map(int,input("N X M 의 행렬의 크기를 정하시오:(N M)형식 ").split())
#     if N<1:
#         print("N값은 1이상 자연수 입력")
#         continue
#     else:
#         if M>100:
#             print("M값은 100이하 자연수 입력")
#             continue
#         else:
#             break
# while True:
#     data = list(map(int, input(f"{N*M}개의 요소를 공백으로 구분 입력").split()))
#     if np.array(data).max()>1000 or np.array(data).min()<1:   # 리스트에서 최대 최소값을 추출할 수 없어서 배열로 변환후 min,max값 확인
#         print("1이상 1000이하의 자연수를 입력하시오")
#         continue
#     else:
#         break
N=4
M=4
data=[1,2,3,4,5,6,7,8,9,10,11,12,14,13,16,15]
# list를 array로
arr = np.array(data).reshape(N,M)
print(arr)
# where 위치 찾기 
# min max array의 최대최소
print(np.min(arr[np.where(arr==np.max(arr))[0][0]]))#행위치[0][0] 
#이거는 최대값이 있는 행을 선택해서 가장 작은값을 출력함

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [14 13 16 15]]
13


In [20]:
np.min(arr,axis=1).max()

13

In [ ]:
N,M = map(int,input("N X M 의 행렬의 크기를 정하시오:(N M)형식 ").split())
result = 0
for i in range(N):
    data = list(map(int,input().split()))
    min_value = min(data)
    result = max(result, min_value)
    
print(result)

# Q70. 
Q69는 함수, 정렬 등의 방법으로 문제를 풀었다. 이 문제를 다중 for문을 사용하여 풀어보세요

In [ ]:
n,m = map(int,input().split())

result = 0
for i in range(n):
    data = list(map(int,input().split()))
    min_value = 10001
    for a in data:
        min_value = min(min_value, a)
    result = max(result,min_value)
print(result)


# Q71. 여행가 A는 N X N 크기의 정사각형 공간에 서 있다. A는 6개의 이동 명령 계획에 따라 움직이게 된다. 이동 명령은 L(왼쪽), R(오른쪽), U(윗쪽), D(아랫쪽)로 구성되며 R R R U D D와 같이 6개이다. 정사각형 공간을 벗어나는 움직임은 무시된다. 언급한 규칙에 따라 N과 이동 명령 계획으로 각각 5와 R R R U D D를 입력하면 A의 행렬에서 위치는 (3, 4)가 된다. 이동 명력 계획서가 주어질 때 A가 최종적으로 도착할 지점의 좌표를 출력하는 프로그램을 작성하시오.
2차원 array에서의 움직임 (1, 1) 시작

In [1]:
import numpy as np

In [6]:
N=5
ar = np.zeros((N,N))
data = list(input().split())
arr=np.array([0,0])
a = {'U':np.array([-1,0]),'D':np.array([1,0]),'R':np.array([0,1]),'L':np.array([0,-1])}
for i in data:
    arr = arr+a[i]
    if arr[0]<0:
        arr[0]=0
    elif arr[0]>N-1:
        arr[0]=N-1
    elif arr[1]<0:
        arr[1]=0
    elif arr[1]>N-1:
        arr[1]=N-1
    else:
        continue
ar[arr[0],arr[1]]=1
print(ar)
print(np.where(ar==1)[0][0]+1,'행', np.where(ar==1)[1][0]+1,'열')


R R R U D D
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3 행 4 열


# Q72.
정수 N이 입력되면 00시 00분 00초부터 N시 59분 59초까지의 모든 시각 중에서 3이 하나라도 포함되는 모든 경우의 수를 구하는 프로그램을 작성하시오.(0<= N <=23)


In [ ]:
00시 00분 03초~
23시 59분 59초
N=7일때 14625번임

In [12]:
t=3
N = int(input("몇시까지?"))
s=0
for i in range(0,N+1):
     for j in range(0,60):
            for k in range(0,60):
#                 if (str(i)+str(j)+str(k)).find('3') !=-1:
#                     s +=1
                if str(t) in str(i) or str(t) in str(j) or str(t) in str(k):
                    s +=1
print(s)

몇시까지?7
14625


# Q73. 행 위치는 1~8로 열 위치는 a ~ h로 표현하는 8 x 8 좌표 평면상에서 특정 위치가 주어졌을 때 아래 조건하에서 그 위치에서 이동할 수 있는 경우의 수를 출력하는 프로그램을 작성하세요.
- 수평으로 두 칸 이동한 뒤에 수직으로 한 칸 이동
- 수직으로 두 칸 이동한 뒤에 수평으로 한 칸 이동
- 8 x 8 좌표 평면을 나갈 수 없음


In [1]:
import numpy as np

In [5]:
m,l= input('숫자행 알파벳열').split()
d={'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7}
m = int(m)-1
l = d[l]

li = {'u1':np.array([-2,-1]),'u2':np.array([-2,1]),'r1':np.array([-1,2]),'r2':np.array([1,2]),'d1':np.array([2,1]),'d2':np.array([2,-1]),'l1':np.array([-1,-2]),'l2':np.array([1,-2])}
s=8
for i in li:
    arr = np.array([m,l])
    arr += li[i]
    if arr[0]<0 or arr[0]>7 or arr[1]<0 or arr[1]>7:
        s-=1
print(s)
    

숫자행 알파벳열2 b
4


# Q74.캐릭터는 매뉴얼에 따라 이동한다. 아래 입력조건에 따라 캐릭터가 방문한 칸의 수를 출력하는 프로그램을 작성하세요.

- 입력조건
  - 첫째 줄에 맵의 세로 크기 N과 가로 크기 M을 공백으로 구분하여 입력 (3 <= N,M <=50)
  - 둘째 줄에 게임 캐릭터가 있는 칸의 좌표 (A,B)와 바라보는 방향 d가 각각 서로 공백으로 구분하여 입력(방향 d의 값으로는 북, 동, 남, 서가 각각 0,1,2,3)
  - 세째 줄에 맵이 육지인지 바다인지에 대한 정보 입력(육지 0, 바다 1) N개의 줄에 맵의 상태가 북쪽으로 부터 남쪽순서대로 각 줄의 데이터는 서쪽부터 동쪽 순서대로 주어진다.
  - 처음에 캐릭터가 위치한 칸의 상태는 항상 육지이다.


- 매뉴얼<BR>
  캐릭터가 있는 장소는 1 X 1 크기의 정사각형으로 이루어진 N X M 크기의 직사각형으로 각각의 칸은 육지 또는 바다이다.캐릭터는 동서남북 중 한 곳을 바라본다. 맵의 각 칸은 (A, B)로 나타낼 수 있고 A는 북쪽으로부터 떨어진 칸의 개수, B는 서쪽으로부터 떨어진 칸의 개수이다.캐릭터는 상하좌우로 움직일 수 있고 바다로 되어 있는 공간에는 갈 수 없다. 캐릭터의 움직임 설정을 위한 매뉴얼은 아래와 같다.
  - 현재 위치에서 현재 방향을 기준으로 왼쪽 방향부터 차례대로 갈 곳을 정한다.
  - 캐릭터의 바로 왼쪽 방향에 아직 가보지 않은 칸이 존재한다면 왼쪽 방향으로 회전한 다음 왼쪽으로 한 칸을 전진한다. 왼쪽 방향에 가보지 않은 칸이 없다면 왼쪽 방향으로 회전만 수행하고 1단계로 돌아간다.
  - 만약 네 방향 모두 이미 가본 칸이거나 바다로 되어 있는 칸인 경우에는 바라보는 방향을 유지한 채로 한 칸 뒤로 가고 1단계로 돌아간다. 단, 이때 뒤쪽 방향이 바다인 칸이라 뒤로 갈수 없는 경우에는 움직임을 멈춘다.


In [2]:
import numpy as np
import pandas as pd

In [3]:
N,M = list(map(int,input().split())) # 3~50
ar = np.random.choice([0,1],size=N*M).reshape(N,M)
ar_p = ar.copy()
print(ar)


5 5
[[1 0 1 0 0]
 [0 0 0 0 1]
 [1 0 1 0 0]
 [0 0 1 1 1]
 [0 0 0 1 0]]


In [20]:
A,B,d = list(map(int,input().split()))
# A=4
# B=3
# d=2

d_p = d
arr= np.array([A-1,B-1]) # 시작위치
ar[A-1,B-1]=1 # 시작위치 마킹
s=1
arrr = {0:np.array([-1,0]),1:np.array([0,1]),2:np.array([1,0]),3:np.array([0,-1])}
while True:
    for i in range(4):
        d -= 1
        if d == -1:
            d = 3 # 서쪽
            if arr[1]==0: # 1열이면
                pass
            else:
                arr = arr + arrr[d] #이동
                if ar[arr[0],arr[1]]==1: # 이동할 곳이 1이면
                    arr = arr - arrr[d] #복귀
                    continue
                else: # 이동할 곳이 1이 아니면
                    ar[arr[0],arr[1]]=1 # 마킹
                    s+=1
                    pass
        elif d == 2:
            if arr[0]==N-1: #끝행
                pass
            else:
                arr = arr + arrr[d]
                if ar[arr[0],arr[1]]==1:
                    arr = arr - arrr[d]
                    continue
                else:
                    ar[arr[0],arr[1]]=1
                    s+=1
                    pass
        elif d == 1:
            if arr[1]==M-1: # 끝열
                pass
            else:
                arr = arr + arrr[d]
                if ar[arr[0],arr[1]]==1:
                    arr= arr - arrr[d]
                    continue
                else:
                    ar[arr[0],arr[1]]=1
                    s+=1
                    pass
        else:
            if arr[0]==0: # 1행
                pass
            else:
                arr = arr + arrr[d]
                if ar[arr[0],arr[1]]==1:
                    arr = arr - arrr[d]
                    continue
                else:
                    ar[arr[0],arr[1]]=1
                    s+=1
                    pass
    d -=2
    if d==-2:
        d=2
        arr = arr + arrr[d]
        d=0
        if ar_p[arr[0],arr[1]]==1:
            arr = arr + arrr[d]
            break
        else:
            ar[arr[0],arr[1]]=1
            s+=1
            continue
    elif d==-1:
        d=3
        arr = arr + arrr[d]
        d=1
        if ar_p[arr[0],arr[1]]==1:
            arr = arr + arrr[d]
            break
        else:
            ar[arr[0],arr[1]]=1
            s+=1
            continue
    else:  # d=0 or d=1
        arr = arr + arrr[d]
        d +=2
        if ar_p[arr[0],arr[1]]==1:
            arr = arr + arrr[d]
            break
        else:
            ar[arr[0],arr[1]]=1
            s+=1
            continue

print(ar_p,'\n')
print(ar, '\n')
print(s)

1 1 1
[[0 1 1 0 0]
 [0 0 0 0 0]
 [1 1 1 1 0]
 [0 1 1 0 1]
 [1 1 1 1 1]] 

[[1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 0]
 [0 1 1 0 1]
 [1 1 1 1 1]] 

3


In [24]:
A,B,d = list(map(int,input().split()))
# A=4
# B=3
# d=2

d_p = d
arr= np.array([A-1,B-1]) # 시작위치
ar[A-1,B-1]=1 # 시작위치 마킹
s=1
arrr = {0:np.array([-1,0]),1:np.array([0,1]),2:np.array([1,0]),3:np.array([0,-1])}
while True:
    
    # 회전
    for i in range(4):
        d -= 1
        if d == -1:
            d = 3 
        arr += arrr[d] #이동
        if arr[0]<0 or arr[0]>N-1 or arr[1]<0 or arr[1]>M-1: # array밖
            arr -= arrr[d] #복귀
            continue
        elif ar[arr[0],arr[1]]!=0: # 이동할 곳이 1이면
            arr -= arrr[d] #복귀
            continue
        else: # 이동할 곳이 array 내이고 1이 아니면
            ar[arr[0],arr[1]]=1 # 마킹
            s+=1
            break
            
    # 뒤돌기        
    d -=2
    if d==-2:
        d=2
        arr += arrr[d]
        d=0
        if ar_p[arr[0],arr[1]]!=0:
            arr += arrr[d]
            
            break
        else: #지나온길
            ar[arr[0],arr[1]]=2 # 2로 마킹하면서 돌아감
            continue
    elif d==-1:
        d=3
        arr += arrr[d]
        d=1
        if ar_p[arr[0],arr[1]]!=0:
            arr += arrr[d]
            
            break
        else:
            ar[arr[0],arr[1]]=2
            continue
    else:  # d=0 or d=1
        arr += arrr[d]
        d +=2
        if ar_p[arr[0],arr[1]]!=0:
            arr += arrr[d]
            
            break
        else:
            ar[arr[0],arr[1]]=2
            continue

print(ar_p,'\n')
print(ar, '\n')
print(s)

1 2 1
[[1 0 1 0 0]
 [0 0 0 0 1]
 [1 0 1 0 0]
 [0 0 1 1 1]
 [0 0 0 1 0]] 

[[1 1 1 1 0]
 [1 1 1 0 1]
 [1 0 1 0 0]
 [0 0 1 1 1]
 [0 0 0 1 0]] 

1


In [14]:
# 스택 : 박스 쌓기 비유, 선입후출 구조
stack = []
stack.append(5)
stack.append(2)
stack.append(3)
stack.append(7)
stack.pop() # 마지막에 들어간, 뒤에서부터 뺌
stack.append(1)
stack.append(4)
stack.pop()
# 5231
print(stack)
print(stack[::-1])

[5, 2, 3, 1]
[1, 3, 2, 5]


In [19]:
# 큐 : 먼저 온 사람이 먼저 들어간다. 선입선출 구조
from collections import deque
queue = deque()
queue.append(5)
queue.append(2)
queue.append(3)
queue.append(7)
queue.popleft() 
queue.append(1)
queue.append(4)
queue.popleft()
print(queue)
queue.reverse()
print(queue)

deque([3, 7, 1, 4])
deque([4, 1, 7, 3])


# Q75 N X M 크기의 얼음 틀로 한번에 만들 수 있는 아이스크림의 개수를 아래 입력조건에 따라 출력하는 프로그램을 DFS(Depth First Search)를 이용하여 작성하세요.
 
- 입력조건
  - 첫번째 줄에 얼음 틀의 세로 길이 N과 가로 길이 M이 주어진다.(1 <= N,M <= 1000)
  - 두번째 줄부터 N+1번째 줄까지 얼음 틀의 형태가 주어진다.
  - 이때 구멍이 뚫려있는 부분은 0 그렇지 않은 부분은 1이다.
  - 구멍이 뚫려 있는 부분끼리 상, 하, 좌, 우로 붙어 있는 경우 서로 연결되어 있는 것으로 간주한다.


재귀랑 스택방식

In [ ]:
상하좌우



In [2]:
N,M = list(map(int,input().split()))
mold=[]
for i in range(M):
    m = list(map(int,input(f'공백으로 구분하여 {N} X {M}맵의 {i+1}번째 행의 칸들이 (0)인지 (1)인지 입력하세요\n').split(' ')))
    mold.append(m)
# 총 아이스크림 개수?
# dfs 검색 해보셈

5 5
공백으로 구분하여 5 X 5맵의 1번째 행의 칸들이 (0)인지 (1)인지 입력하세요
0 0 1 1 0
공백으로 구분하여 5 X 5맵의 2번째 행의 칸들이 (0)인지 (1)인지 입력하세요
0 0 0 1 1
공백으로 구분하여 5 X 5맵의 3번째 행의 칸들이 (0)인지 (1)인지 입력하세요
1 1 1 1 1
공백으로 구분하여 5 X 5맵의 4번째 행의 칸들이 (0)인지 (1)인지 입력하세요
0 0 1 1 1
공백으로 구분하여 5 X 5맵의 5번째 행의 칸들이 (0)인지 (1)인지 입력하세요
1 1 0 0 0


In [3]:
mold

[[0, 0, 1, 1, 0],
 [0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1],
 [0, 0, 1, 1, 1],
 [1, 1, 0, 0, 0]]

In [5]:
def dfs(x,y):
    if x<0 or x>N-1 or y<0 or y>M-1:
        return False
    
    elif mold[x][y]==0:
        mold[x][y]=1
        dfs(x+1,y)
        dfs(x-1,y)
        dfs(x,y+1)
        dfs(x,y-1)
        return True
    
    return False #원래 1인경우
s=0
for i in range(N):
    for j in range(M):
        if dfs(i,j)==True:
            s+=1
print('얼음개수',s)

얼음개수 4


In [ ]:
N=5
M=5
00110
00011
11111
00111
11000
4개

In [14]:
def recursive_function(i):
    if i == 5:
        return
    print(i,'번째 재귀함수에서', i+1,'번째 재귀함수를 호출합니다.')
    recursive_function(i+1)
    print(i,'번째 재귀함수를 호출합니다.')
recursive_function(1)

1 번째 재귀함수에서 2 번째 재귀함수를 호출합니다.
2 번째 재귀함수에서 3 번째 재귀함수를 호출합니다.
3 번째 재귀함수에서 4 번째 재귀함수를 호출합니다.
4 번째 재귀함수에서 5 번째 재귀함수를 호출합니다.
4 번째 재귀함수를 호출합니다.
3 번째 재귀함수를 호출합니다.
2 번째 재귀함수를 호출합니다.
1 번째 재귀함수를 호출합니다.


# Q76. 재귀함수를 이용하여 10! 출력하세요

In [18]:
def factorial_iterative(n):
    result = 1
    for i in range(1,n+1):
        result *=i
    return result
factorial_iterative(10)

3628800

In [24]:
def fac(n):
    if n==0 or n==1:
        return 1
    else:
        return fac(n-1)*n
fac(10)

3628800

#  Q77.N X M 크기의 미로에는 여러마리의 괴물이 있어 이를 피해 탈출해야 한다. 주인공의 위치는 (0,0)이고 미로의 출구는 (N-1,M-1)의 위치에 존재하며 한번에 한칸씩 이동할 수 있다. 괴물이 있는 부분은 0, 없는 부분은 1로 표시되어 있으며 미로는 반드시 탈출할 수 있는 형태로 제시된다. 주인공이 탈출하기 위해 움직여야 하는 최소 칸의 개수를 구하세요. 칸을 셀 때는 시작 칸과 마지막 칸을 모두 포함하여 계산하고 입력 조건은 아래와 같다.(BFS를 이용)
- 첫째 줄에 두 정수 N,M(4<=N,M<=200)이 주어진다. 
- 다음 N개의 줄에는 각각 M개의 정수(0 혹은 1)로 미로의 정보가 주어진다. 각각의 수들은 공백없이 붙여서 입력으로 제시된다. 
- 또한 시작칸과 마지막칸은 항상 1이다.



In [ ]:
맵 전체 훑기 

탈출하기 위한 최소 칸의 수는? 시작과 마지막 포함
5 5
11011
01011
01111
11011
10111
1은 길 
0은 괴물
답 9 
큐 사용
선입선출

In [96]:
N,M = list(map(int,input().split()))
f=[]
for i in range(M):
    m = list(map(int,input(f'공백으로 구분하여 {N} X {M}맵의 {i+1}번째 행의 칸들이 (0)인지 (1)인지 입력하세요\n').split(' ')))
    f.append(m)

5 5
공백으로 구분하여 5 X 5맵의 1번째 행의 칸들이 (0)인지 (1)인지 입력하세요
1 1 0 1 1
공백으로 구분하여 5 X 5맵의 2번째 행의 칸들이 (0)인지 (1)인지 입력하세요
0 1 0 1 1
공백으로 구분하여 5 X 5맵의 3번째 행의 칸들이 (0)인지 (1)인지 입력하세요
0 1 1 1 1
공백으로 구분하여 5 X 5맵의 4번째 행의 칸들이 (0)인지 (1)인지 입력하세요
1 1 0 1 1
공백으로 구분하여 5 X 5맵의 5번째 행의 칸들이 (0)인지 (1)인지 입력하세요
1 0 1 1 1


In [8]:
N,M=5,5
f=[[1,1,0,1,1],[0,1,0,1,1],[0,1,1,1,1],[1,1,0,1,1],[1,0,1,1,1]]

In [10]:
from collections import deque

# 방향 정보(상하좌우)
dx = [-1,1,0,0]
dy = [0,0,-1,1]

# 출발 노드
q = deque()
q.append([0,0])
# 혹은 deque([(0,0)])

while q :
  # 큐에서 하나의 원소를 꺼내서 출력
  x, y = q.popleft()

  # 꺼낸 원소와 인접노드 확인
  for i in range(len(dx)):
    nx = x+dx[i]
    ny = y+dy[i]

    # 범위를 벗어난 노드 무시
    if nx>N-1 or ny>M-1 or nx<0 or ny<0 :
        continue

    # 아직 방문하지 않은 노드라면
    # 처음 방문하는 경우가 바로 최단거리다
    if f[nx][ny]==1:
        q.append((nx,ny))
        f[nx][ny] = f[x][y]+1 # 직전 노드+1
        

print(f[N-1][M-1])

9


# 소수란 2보다 큰 자연수 중에서 1과 자신을 제외한 자연수로 나누어 떨어지지 않은 자연수이다. 어떠한 자연수가 소수인지 아닌지 판별하는 프로그램을 작성하세요.

In [11]:
n = int(input())
for i in range(2,n):
    if n%i==0:
        print(n,': 소수x')
        break
    else:
        print(n,': 소수')
        break

31
31 : 소수


In [15]:
def prime(n):
    is_d = [ n%i == i for i in range(2,n) ]
    print(is_d)
    if any(is_d or (n in [0,1])):
        print(n,': 소수x')
    else:
        print(n,': 소수')

In [16]:
prime(31)

[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
31 : 소수


# Q79.
M 이상 N 이하의 소수를 모두 출력하는 프로그램을 작성하세요.
- 입력조건
  - 첫째 줄에 자연수 M과 N이 빈칸을 사이에 두고 주어진다.(1<=M<=N<=1,000,000)
  - 단 M이상 N 이하의 소수가 하나 이상 있는 입력만 주어진다.


In [ ]:
1<=M<=n<=N<=1000000
소수 n 출력

In [ ]:
str 적용 해결

In [2]:
def p(M,N):
    li=[]
    for n in range(M,N+1):
        is_p = [ n%i == i for i in range(2,n)]
        if any(is_p or (n in [0,1])): 
            continue
        else:
            li.append(n)
    return li

M,N = list(map(int, input().split(' ')))
p(M,N)

1 100


TypeError: 'bool' object is not iterable

In [11]:
M,N = list(map(int, input().split(' ')))
# if any(is_d):
#         print('1<=M<= n <=N<=1,000,000 소수 n 존재x')
p(M,N)

1 100


TypeError: 'bool' object is not iterable

In [25]:
# n 이 소수면 True
def prime(n):
    is_d = [ n%i == i for i in range(2,n) ]
#     print(is_d)
    if any(is_d or (n in [0,1])):
        return False
    else:
        return True

li=[]
# is_d=[]
M,N = list(map(int, input().split(' ')))
is_d = [ prime(i) for i in range(M,N)]
while True:
    if any(is_d):
        print('1<=M<= n <=N<=1,000,000 소수 n 존재x')
        continue
    else:
        for j in range(M,N):
            for k in range(2,j):
                if j%k==0:
                    break
                else:
                    li.append(j)
                    break
    print(li)
    break

1 100
[]


TypeError: 'bool' object is not iterable

# Q80.

암호는 서로 다른 L개의 알파벳 소문자들로 구성되며 최소 한 개의 모음(a, e, i, o, u)과 최소 두 개의 자음으로 구성되어 있다고 알려져 있다. 또한 정렬된 문자열을 선호하는 직원들의 성향으로 미루어 보아 암호를 이루는 알파벳이 암호에서 증가하는 순서로 배열되었을 것이라고 추측된다. 즉, abc는 가능성이 있는 암호이지만 bac는 그렇지 않다. 새 보안 시스템에서 직원들이 암호로 사용했을 법한 문자의 종류는 C가지가 있다고 한다. 이 알파벳을 입수한 james, kevin 형제는 직원들의 방에 침투하기 위해 암호를 추측해 보려고 한다. C개의 문자들이 모두 주어졌을 때, 가능성 있는 암호들을 모두 구하는 프로그램을 다음 사항에 유의하여 작성하시오.
- 첫째 줄에 두 정수 L, C가 주어진다. (3 ≤ L ≤ C ≤ 15) 다음 줄에는 C개의 문자들이 공백으로 구분되어 주어진다. 주어지는 문자들은 알파벳 소문자이며, 중복되는 것은 없다.
- 각 줄에 하나씩, 사전식으로 가능성 있는 암호를 모두 출력한다.


In [ ]:
#이해가 안되는딩 . .  총 C 개의 알파벳을 입력하고 그중에서 L개의 알파벳으로 조합을 만드는건가

In [ ]:
l 개의 소문자
최소 한개의 모음 2개의 자음
중복불가 순서대로 배치
총 c 가지 조합
26개의 알파벳
5개의 모음
21개의 자음

In [4]:
from itertools import combinations

In [69]:
v=['a','e','i','o','u']
while True:
    L,C = map(int,input().split(' '))
    D = list(input(f'{C}개의 알파벳 입력').split(' '))
    
    # 모음
    vo=[]
    for i in v:
        if i in D:
            vo.append(i)
        
    if len(set(D)) != C:
        print(f'중복없이 {C}개 다시 입력')
        continue
    elif len(vo)<1:
        print('모음 한 개 이상 입력')
        continue
    elif C-len(vo)<2:
        print('자음 두 개 이상 입력')
    else:
        break
    
t = list(combinations(D,L))
v_n=0
li=[]
for i in range(len(t)):
    for j in t[i]:
        if j in v:#조합 내 모음 있으면 v_n +1
            v_n +=1
        
    if v_n<1 or L-v_n<2:
        v_n=0
        continue
    else:
        w = sorted(t[i])
        w = ''.join(w)
        li.append(w)
        v_n=0

for i in range(0,len(li)):
    print(li[i])


4 6
6개의 알파벳 입력a t e w s i
aetw
aest
astw
aitw
aist
aesw
aisw
estw
eitw
eist
istw
eisw


# Q81.
파이썬의 itertools 라이브러리를 활용하여 리스트 data = ['A','B','C']로 부터 아래 문제를 풀어보세요.
- 3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용안됨)
- 3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용)
- 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용안됨)
- 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용)


In [70]:
itertools

Object `itertools` not found.


In [1]:
import itertools

# from itertools import 

data = ['A','B','C']
#1
a = list(itertools.permutations(data,3))
#2
b = list(itertools.product(data,repeat=3))
#3
c = list(itertools.combinations(data,3))
#4
d = list(itertools.combinations_with_replacement(data,3))
print(f'3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용안됨):\n{a}','\n',f'3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용):\n{b}','\n', 
      f'3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용안됨):\n{c}','\n', f'3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용):\n{d}')

3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용안됨):
[('A', 'B', 'C'), ('A', 'C', 'B'), ('B', 'A', 'C'), ('B', 'C', 'A'), ('C', 'A', 'B'), ('C', 'B', 'A')] 
 3개를 뽑아 나열하는 모든 경우를 출력하세요(중복 허용):
[('A', 'A', 'A'), ('A', 'A', 'B'), ('A', 'A', 'C'), ('A', 'B', 'A'), ('A', 'B', 'B'), ('A', 'B', 'C'), ('A', 'C', 'A'), ('A', 'C', 'B'), ('A', 'C', 'C'), ('B', 'A', 'A'), ('B', 'A', 'B'), ('B', 'A', 'C'), ('B', 'B', 'A'), ('B', 'B', 'B'), ('B', 'B', 'C'), ('B', 'C', 'A'), ('B', 'C', 'B'), ('B', 'C', 'C'), ('C', 'A', 'A'), ('C', 'A', 'B'), ('C', 'A', 'C'), ('C', 'B', 'A'), ('C', 'B', 'B'), ('C', 'B', 'C'), ('C', 'C', 'A'), ('C', 'C', 'B'), ('C', 'C', 'C')] 
 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용안됨):
[('A', 'B', 'C')] 
 3개를 뽑아 순서에 상관없이 나열하는 모든 경우를 출력하세요(중복 허용):
[('A', 'A', 'A'), ('A', 'A', 'B'), ('A', 'A', 'C'), ('A', 'B', 'B'), ('A', 'B', 'C'), ('A', 'C', 'C'), ('B', 'B', 'B'), ('B', 'B', 'C'), ('B', 'C', 'C'), ('C', 'C', 'C')]


In [78]:
itertools?

# Q82.
아래사항을 참조, 파이썬의 heapq 라이브러리를 활용하여 주어진 리스트 iterable = [1,3,5,7,9,2,4,6,8,0]을 힙 정렬하여 출력하세요.
- 최소 힙 : heap 역할을 할 빈 리스트를 선언해주고, heappush 메소드의 매개변수로 해당 리스트와 추가하고자 하는 값을 넣어주면 리스트에 힙 정렬이 되게 원하는 값이 삽입된다.
- 최대 힙 : heapq에서는 최대 힙을 제공하지 않는다. 따라서 부호를 변경하는 방법을 사용해서 최대 힙을 구현한다.


In [20]:
from heapq import heappush, heappop
# 최소 힙
iterable = [1,3,5,7,9,2,4,6,8,0]

heap = []
for i in iterable:
    heappush(heap, i)

sorted_nums = []
while heap:
    sorted_nums.append(heappop(heap))

sorted_nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
# 최대 힙
iterable = [1,3,5,7,9,2,4,6,8,0]
heap = []

for i in iterable:
    heappush(heap, -i)

sorted_nums = []
while heap:
    sorted_nums.append(-heappop(heap))

sorted_nums

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Q83.
파이썬 bisect 라이브러리를 활용하여 리스트 a = [1,2,3,3,3,4,4,8,9] 로 부터 아래 문제들을 풀어보세요.
- 값이 4인 데이터 개수 출력
- 값이 [-1,3] 범위에 있는 데이터 개수 출력


In [2]:
import bisect # 인덱스 출력

In [3]:
a = [1,2,3,3,3,4,4,8,9]
r = bisect.bisect_right(a,4) #오른쪽에서부터 인덱스
l = bisect.bisect_left(a,4) #왼쪽에서부터 인덱스 
r-l 

2

In [5]:
bisect.bisect_right(a,3)-bisect.bisect_left(a,-1)

5

# Q84.
파이썬 collections 라이브러리를 활용하여 아래 문제들을 풀어보세요.<br>
deque는 스택이나 큐의 기능을 모두 포함하며 스택 혹은 큐 자료구조의 대용으로 사용할 수 있다
- 리스트 [2,3,4]에 첫번째 자리에는 1, 마지막 자리에는 5를 삽입하여 출력
- 리스트 [2,3,4]에서 2와 4를 삭제하고 1과 6을 삽입하여 리스트 [1,3,6]을 출력
- 리스트 ['red','blue','red','green','blue','blue']에서 'blue'와 'green'의 갯수를 출력
- 리스트 ['red','blue','red','green','blue','blue']에서 칼러별 개수를 사전 타입으로 출력


In [13]:
import collections

li = [2,3,4]
q = collections.deque(li)
q.appendleft(1)
q.append(5)
q

deque([1, 2, 3, 4, 5])

In [15]:
q = collections.deque(li)
q.popleft()
q.pop()
q.appendleft(1)
q.append(6)
q

deque([1, 3, 6])

In [21]:
li = ['red','blue','red','green','blue','blue']
c = collections.Counter(li)
c['blue'], c['green']

(3, 1)

In [17]:
li = ['red','blue','red','green','blue','blue']
c = collections.Counter(li)
c

Counter({'red': 2, 'blue': 3, 'green': 1})

# Q85.
파이썬 math 라이브러리를 활용하여 아래 문제들을 풀어보세요.
- 10에 대한 팩토리얼, 제곱근, 최대 공약수 를 출력
- pi, e 값 출력
- 10의 3 제곱 출력
- 2에 대한 지수함수 값 및 그 출력값에 로그함수를 적용한 결과 출력


In [2]:
import math

In [4]:
display(math.factorial(10), math.sqrt(10), math.gcd(10, 5) )

display(math.pi, math.e)
display(math.pow(10,3))
display(math.exp(10), math.log(math.exp(10)))

3628800

3.1622776601683795

5

3.141592653589793

2.718281828459045

1000.0

22026.465794806718

10.0

# Q86.
1 ~ 1000,000 사이의 홀수로 구성된 리스트에서 [1, 4, 9, 16, 25,... ]와 같이 구간 합을 구한다. 구간 합으로 구성된 리스트에서 n번째 원소에서 m번째 원소의 차이를 구하는 프로그램을 작성하고 n=10, m=5일때의 값을 구하세요.


In [3]:
# 홀수 리스트
li=[]
for i in range(1,1000000):
    if i%2 != 0:
        li.append(i)

# 수열 리스트
lis=[]
s=0
for j in li:
    s += j
    lis.append(s)
    
def nm(li, n, m):
    return li[n-1]-li[m-1]

print(nm(lis, 10, 5))

75


In [4]:
print(lis[:10])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# Q87.
각 자리가 숫자(0부터 9)로만 이루어진 문자열 S가 주어졌을 때 왼쪽부터 오른쪽으로 하나씩 모든 숫자를 확인하며 숫자 사이에 'X' 혹은 '+' 연산자를 넣어 결과적으로 만들어질 수 있는 가장 큰 수를 구하는 프로그램을 작성하세요. 단 가장 큰 수는 항상 20억 이하의 정수가 되도록 입력이 주어진다.

((((0+2) X 9) X 8) X 4) = 576


In [ ]:
임의의 문자열 S = 
기본적으로 곱하기
if 0앞뒤로는 무조건 +
2000000000 이하의 정수 중에 가장 큰 수

In [43]:
S='029849999999'

if S[0]=='0':
    result = 0
else:
    result = 1
        
for i in range(len(S)-1):
    if int(S[i]) == 0 or int(S[i+1]) == 0 or int(S[i])==1:
        result += int(S[i+1])
    else:
        result *= int(S[i+1])
        if result>2000000000:
            result= result//int(S[i+1]) +int(S[i+1])
            
result

306110025

# Q88.

공포도가 높은 모험가는 쉽게 공포를 느껴 위험 상황에서 제대로 대처할 능력이 떨어진다. 모험가 그룹을 안전하게 구성하고자 공포도가 X인 모험가는 반드시 X명 이상으로 구성한 모험가 그룹에 참여해야 여행을 떠날 수 있도록 규정한다.N명의 모험가에 대한 정보가 주어졌을 때 여행을 떠날 수 있는 그룹 수의 최댓값을 구하는 프로그램을 작성하세요.

N = 5   첫째줄에 모험가 수 이 주어짐<BR> 
2 3 1 2 2   둘째줄에 각 모험가의 공포도의 값이 N이하의 자연수로 주어진다<BR>
출력 : 그룹 수 최댓값 2


In [1]:
N = 5
a = '23122'

In [2]:
def adv(a):
    li=[]
    for i in range(len(a)):
        li.append(int(a[i]))
        li.sort(reverse=True)
    j=0 # 인덱스
    s=0 # 그룹 수
    b=len(li)
    while True:
        b -= li[j]
        j += li[j]
        s+=1
        if b<li[j]:
            break
        elif b==li[j]:
            s+=1
            break
    return s
        
adv(a)

2

# Q89.
0과 1로만 이루어진 문자열 S가 있다. 문자 S에 있는 모든 숫자를 전부 같게 만들려고 한다. 허용된 행동은 S에서 연속된 하나 이상의 숫자를 잡고 모두 뒤집는 것이다. 주어진 입력조건하에서 모두 같은 숫자로 만들기 위한 행동의 최소 횟수를 출력하세요.
- 입력 : 첫째 줄에 0과 1로만 이루어진 문자열 S가 주어지고 S는 100만보다 작다.


In [ ]:
6자리
101010 세번이 가장 많이 뒤집는거임.
111111
100000
101111
110011
110111
111000
111100

In [ ]:
# 0, 1 로 바꾸는 두가지 를 다 구해서 작은거 출력 하는방법 있네 

In [2]:
while True:
    S=input()
    if int(S)>=1000000:
        print('다시.')
    else:
        n=0
        for i in range(len(S)-1):
            if S[i]==S[i+1]:
                continue
            else:
                n+=1
        d = divmod(n,2)
        if d[1]==1:
            print(d[0]+1)
        else:
            print(d[0])
        break


111000
1


In [ ]:
a = input()

# 1, 0 을 기준으로 문자열을 나눠 리스트 만들기
b = [bb for bb in a.split("1") if bb]
c = [cc for cc in a.split("0") if cc]

print(b,c)
print(min(len(b), len(c)))

# Q90.
N개의 동전을 이용하여 만들 수 없는 양의 정수 금액 중 최솟값을 구하는 프로그램을 작성하세요.

<입력 조건>

첫째 줄에는 동전의 개수를 나타내는 양의 정수 N이 주어진다 (1<=N<=1,000)
둘째 줄에는 각 동전의 화폐 단위를 나타내는 N개의 자연수가 주어지며 각 자연수는 공백으로 구분한다. (각 화폐단위는 1,000,000 이하)


In [ ]:
5 개 
1 2 3 4 5 화폐단위
16 을 못 출력함

In [ ]:
# 조합으로 풀었네 from itertools import combination

In [2]:
from itertools import combinations
N = 5
n_li = 1, 2, 3, 4, 5
na_li = []; result = []; be=1

for i,_ in enumerate(n_li):
    na_li.append(list(combinations(n_li,i+1)))
# print(na_li)
for i,j in enumerate(na_li):
    for k in j:
        result.append(sum(k))
# print(result)
while True:
    if be not in list(set(result)):
        print('모든 조합:',list(set(result)))
        print('만들 수 없는 양의 정수 금액 중 최솟값:',be)
        break
    else:
        be +=1

[[(1,), (2,), (3,), (4,), (5,)], [(1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)], [(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5)], [(1, 2, 3, 4), (1, 2, 3, 5), (1, 2, 4, 5), (1, 3, 4, 5), (2, 3, 4, 5)], [(1, 2, 3, 4, 5)]]
[1, 2, 3, 4, 5, 3, 4, 5, 6, 5, 6, 7, 7, 8, 9, 6, 7, 8, 8, 9, 10, 9, 10, 11, 12, 10, 11, 12, 13, 14, 15]
모든 조합: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
만들 수 없는 양의 정수 금액 중 최솟값: 16


# Q91. 클래스 Country와 Korea를 완성하여 아래와 같이 출력하세요. 단, obj=Korea('한국',5,'서울')를 만들어서 활용 (상속)

class Country:
    def __init__(self, name, pop, capital):


class Korea(Country):
    
```
[출력]
한국 인구는 5천만명이며 수도는 서울입니다.
1인당 gnp는 USD 3만입니다.

[출력]
미국 인구는 30천만명이며 수도는 워싱턴입니다.
1인당 gnp는 USD 5만입니다.

```

In [2]:
class Country:
    def __init__(self, name, pop, capital):
        self.name = name
        self.pop = pop
        self.capital = capital
        
        
class Korea(Country):
    def pr(self, gnp):
        self.gnp = gnp
        return f'{self.name} 인구는 {self.pop}명이며 수도는 {self.capital}입니다. 1인당 gnp는 USD {self.gnp}입니다.'
    
        

a = Korea('한국', '5천만', '서울')
a.pr('3만')
    

'한국 인구는 5천만명이며 수도는 서울입니다. 1인당 gnp는 USD 3만입니다.'

# Q.92 사칙연산 기능을 포함하는 모듈을 작성 후 임포트해서 사칙연산을 수행하세요우

In [11]:
with open('cal4.py','w') as f:
    f.write('''
def cal(x,y):
    return x + y, x * y, x - y, round(x / y,2)
print(cal(5,3))
''')


In [12]:
import cal4

(8, 15, 2, 1.67)


In [9]:
with open('cal3.py','w') as f:
    f.write('''
def calall(x,y):
    return x + y, x*y, x-y, x/y
if __name__ == "__main__":
    print(calall(3,4))
''')


In [10]:
!python cal3.py

(7, 12, -1, 0.75)


In [13]:
import cal3

In [14]:
cal3.calall(5,10)

(15, 50, -5, 0.5)

In [3]:
import cal
dir(cal)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'div',
 'minus',
 'mul',
 'plus']

In [16]:
import cal
print(cal.div(2,2))
print(cal.minus(2,2))
print(cal.mul(2,2))
print(cal.plus(2,2))

1.0
0
4
4


# Q93.Player가 3승할때까지 계속하는 가위바위보 프로그램

In [5]:
import numpy as np
import random
c=['가위','바위','보']

def game():
    n,w,d,l=0,0,0,0
    while w != 3:
        print('가위바위보하자.')
        a = np.random.choice(c)
        b = input('가위, 바위, 보를 입력하세요')
        if c.index(b) == c.index(a):
            n+=1
            d+=1
            print(n,'전')
            print('비김')
        elif c.index(b)>c.index(a):
            n+=1
            w+=1
            print(n,'전')
            print('이김')
        else:
            n+=1
            l+=1
            print(n,'전')
            print('짐')
    print(n,'전',d,'무',l,'패만에',w,'승')
    
game()           

가위바위보하자.
가위, 바위, 보를 입력하세요보
1 전
이김
가위바위보하자.
가위, 바위, 보를 입력하세요보
2 전
비김
가위바위보하자.
가위, 바위, 보를 입력하세요보
3 전
비김
가위바위보하자.
가위, 바위, 보를 입력하세요보
4 전
이김
가위바위보하자.
가위, 바위, 보를 입력하세요보
5 전
비김
가위바위보하자.
가위, 바위, 보를 입력하세요보
6 전
비김
가위바위보하자.
가위, 바위, 보를 입력하세요보
7 전
이김
7 전 4 무 0 패만에 3 승


# Q94. 2개의 주식데이터를 가져와서 아래와 같이 결합한 후 다음 사항을 수행하세요. 

- df1과 df2의 교집합만 출력되도록 결합하여 df3에 저장하고 출력
- df3에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df4 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)
- df2의 name 컬럼을 stock_name으로 변경한 후 df1과 df2를 stock_name을 기준으로 결합(합집합)


In [2]:
import pandas as pd

df1 = pd.read_excel('./data/stock_price.xlsx', index_col='id')
df2 = pd.read_excel('./data/stock valuation.xlsx', index_col='id')

In [11]:
df3 = df1.join(df2, how='inner')
df3

stock_name          value   price    name           eps     bps  \
id                                                                       
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
130960  15.695091  1.829178  
139480  13.931338  0.860437  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
204210  40.802348  0.651359

In [12]:
df3.columns

Index(['stock_name', 'value', 'price', 'name', 'eps', 'bps', 'per', 'pbr'], dtype='object')

In [13]:
df4 = df3.drop('name', axis=1, inplace=False)
df4 = df4[(df4.eps<3000)|(df4.stock_name=='이마트')]
df4

stock_name          value   price           eps     bps        per  \
id                                                                          
139480        이마트  239230.833333  254500  18268.166667  295780  13.931338   
204210     모두투어리츠    3093.333333    3475     85.166667    5335  40.802348   

             pbr  
id                
139480  0.860437  
204210  0.651359

In [21]:
df2.rename(columns={'name':'stock_name'}, inplace=True)
df2

stock_name           eps     bps        per       pbr
id                                                          
130960     CJ E&M   6301.333333   54068  15.695091  1.829178
136480         하림    274.166667    3551  11.489362  0.887074
138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
139480        이마트  18268.166667  295780  13.931338  0.860437
145990        삼양사   5741.000000  108090  14.283226  0.758627
161390      한국타이어   5648.500000   51341   7.453306  0.820007
181710  NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
185750        종근당   3990.333333   40684  25.185866  2.470259
204210     모두투어리츠     85.166667    5335  40.802348  0.651359
207940   삼성바이오로직스   4644.166667   60099  89.790059  6.938551

In [25]:
df1

stock_name          value   price
id                                      
128940       한미약품   59385.666667  421000
130960     CJ E&M   58540.666667   98900
138250      엔에스쇼핑   14558.666667   13200
139480        이마트  239230.833333  254500
142280     녹십자엠에스     468.833333   10200
145990        삼양사   82750.000000   82000
185750        종근당   40293.666667  100500
192400      쿠쿠홀딩스  179204.666667  177500
199800         툴젠   -2514.333333  115400
204210     모두투어리츠    3093.333333    3475

In [27]:
df1.merge(df2, on='stock_name', how='outer')

stock_name          value   price           eps     bps        per       pbr
0     CJ E&M   58540.666667   98900   6301.333333   54068  15.695091  1.829178
1        이마트  239230.833333  254500  18268.166667  295780  13.931338  0.860437
2        삼양사   82750.000000   82000   5741.000000  108090  14.283226  0.758627
3        종근당   40293.666667  100500   3990.333333   40684  25.185866  2.470259
4     모두투어리츠    3093.333333    3475     85.166667    5335  40.802348  0.651359

# Q95. 아래 사항을 수행하세요.
- 주어진 텍스트에서 단어 빈도 카운트
- 빈도순으로 단어별 카운트를 사전형식으로 반환, 가장 빈도가 높은 단어 5개를 출력

In [1]:
import re
with open("./data/text.txt","r", encoding='utf-8') as f:
    text = f.read()
f.close

# print(text)
text = re.sub('[^가-힣]+', ' ', text)
text

' 카카오가 시간의 다음 카카오톡 먹통 피해사례 접수를 시작한다 유료 뿐 아니라 무료 이용자에도 피해 보상하는 방안을 검토 중인데 전례가 없었던 일인 만큼 실질적 보상까지는 상당한 시간이 걸릴 전망이다 홍은택 카카오 대표는 일 경기 성남시 판교사옥에서 열린 간담회에서 유료 서비스 이용자뿐 아니라 이번 장애로 피해 입은 이용자와 파트너 다양한 이해관계자에 대한 보상을 검토하겠다 고 밝혔다 이에 카카오는 이날부터 주간 피해신고 채널을 열고 사례를 모은다 이용자들이 서비스명 피해사례 근거자료를 접수하면 이를 바탕으로 보상안을 수립한다는 방침이다 앞서 카카오 쇼핑 웹툰 멜론 등 유료 서비스는 이용권 유효기간 연장 및 캐시지급 등의 피해보상안을 발표했다 다만 무료 이용자의 경우 보상을 받기까진 오랜 시간이 걸릴 전망이다 홍 대표는 무료 서비스 이용자는 보상 선례도 없고 기준도 없어 다양한 사례를 보고 판단하겠다 며 사례 확인 후 정책을 만들어야 해서 시간이 걸릴 것 이라고 말했다 카카오에 보상을 요구하는 목소리는 거세다 전날 택시 개 단체는 카카오 먹통으로 손해를 본 일반 중개택시에도 피해보상 하라 라고 지적했다 대리운전 기사도 피해사례 취합에 나섰다 가장 늦게까지 복구가 안 된 다음 카카오메일과 톡채널 이용자들의 불만도 빗발친다 서울 강남구에 근무하는 씨는 중요 행사를 앞두고 있는데 회사 메일로 다음을 쓰고 있어 이번주 내내 업무가 마비됐다 고 토로했다 카카오가 보상안을 마련하더라도 성난 민심을 잠재울수 있을진 미지수다 지난해 는 전국 네트워트 장애 사고 발생 당시 소상공인에 평균 원 개인 기업 가입자에 회선당 원 안팎의 피해보상안을 발표했으나 보상 수준이 턱없이 낮다는 평가를 받았다 특히 소상공인들은 매출 손실에 대한 보상안이 빠졌다고 반발했다 카카오 보상안이 미진할 경우 대규모 공동소송이 벌어질 수 있다 이미 법무법인 파트너스 가 연 손해배상 청구 소송인단 카페 가입자가 명에 달한다 는 무료 서비스여도 사업자 과실로 피해가 발생하면 민법상 채무불이행에 대한 손해배

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from konlpy.tag import Okt

okt = Okt()
morph = okt.pos(text)
li = []
for word, tag in morph:
    if ((tag=='Noun')|(tag=='Adjective'))&(len(word)>1):
        li.append(word)
        
print(morph)
print(li)

OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
OpenJDK 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed.


[('카카오', 'Noun'), ('가', 'Josa'), ('시간', 'Noun'), ('의', 'Josa'), ('다음', 'Noun'), ('카카오', 'Noun'), ('톡', 'Noun'), ('먹통', 'Noun'), ('피해', 'Noun'), ('사례', 'Noun'), ('접수', 'Noun'), ('를', 'Josa'), ('시작', 'Noun'), ('한', 'Josa'), ('다', 'Adverb'), ('유료', 'Noun'), ('뿐', 'Noun'), ('아니라', 'Adjective'), ('무료', 'Noun'), ('이용자', 'Noun'), ('에도', 'Josa'), ('피해', 'Noun'), ('보상', 'Noun'), ('하는', 'Verb'), ('방안', 'Noun'), ('을', 'Josa'), ('검토', 'Noun'), ('중', 'Noun'), ('인데', 'Josa'), ('전례', 'Noun'), ('가', 'Josa'), ('없었던', 'Adjective'), ('일인', 'Noun'), ('만큼', 'Noun'), ('실질', 'Noun'), ('적', 'Suffix'), ('보상', 'Noun'), ('까지는', 'Josa'), ('상당한', 'Adjective'), ('시간', 'Noun'), ('이', 'Josa'), ('걸릴', 'Verb'), ('전망', 'Noun'), ('이다', 'Josa'), ('홍은택', 'Noun'), ('카카오', 'Noun'), ('대표', 'Noun'), ('는', 'Josa'), ('일', 'Noun'), ('경기', 'Noun'), ('성남시', 'Noun'), ('판교', 'Noun'), ('사옥', 'Noun'), ('에서', 'Josa'), ('열린', 'Verb'), ('간담', 'Noun'), ('회', 'Noun'), ('에서', 'Josa'), ('유료', 'Noun'), ('서비스', 'Noun'), ('이용자', 'Noun'), ('뿐', '

In [3]:
import pandas as pd
from collections import Counter
from matplotlib import rc
import matplotlib.pyplot as plt
import seaborn as sns

rc('font', family = 'Malgun Gothic') #한글 폰트 설정
plt.rcParams['axes.unicode_minus'] = False #마이너스 부호 출력 설정

count = Counter(li)
data = dict(count.most_common())
series = pd.Series(data)
df = pd.DataFrame(series, columns=['cnt'])
df10 = df.sort_values(by='cnt', ascending = False)[:5]
df10.reset_index(inplace=True)
df10
# list(data.keys())[:5]

index  cnt
0    보상   18
1   카카오   14
2    피해   13
3   이용자    7
4    사례    6