<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#판다스" data-toc-modified-id="판다스-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>판다스</a></span></li><li><span><a href="#데이터프레임" data-toc-modified-id="데이터프레임-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>데이터프레임</a></span></li></ul></div>

## 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조
- contents
    - Series(변환, 인덱스 구조, 원소 선택)
    - DataFrame(변환, 행인덱스/열이름 지정, 삭제, 선택, 추가, 변경, 전치, 인덱스 활용)
   

In [5]:
# 딕셔너리를 시리즈로
import pandas as pd
dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
# 리스트를 시리즈로
list_data = ['2019-07-02', 3.14, 'ABC', 100, True]
sr = pd.Series(list_data, index=list("abcde"))
#sr = pd.Series(list_data) 기본 인덱스 0,1,2,3 ...
sr

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [9]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-07-02' 3.14 'ABC' 100 True]


In [10]:
# 튜플을 시리즈로
tup_data = ('kevin', '2019-077-02', '남', True)
sr = pd.Series(tup_data, index = ['이름', '생년월일','성별', '학생여부'])
print(sr)

이름            kevin
생년월일    2019-077-02
성별                남
학생여부           True
dtype: object


In [17]:
print(sr[0])
print(sr['이름'])
print(sr[[1,2]]) # 두개라 리스트로 묶어줘야됨
# print(sr[1,2]) Error

kevin
kevin
생년월일    2019-077-02
성별                남
dtype: object


In [20]:
import numpy as np
data = np.arange(1000, 5000, 1000)
state = ['Califonia', 'Ohio', 'Oregon','Texas']
obj = pd.Series(data, index = state)
obj

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
dtype: int32

In [21]:
obj.name = 'population'
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [22]:
obj.Califonia = np.nan  # null값
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [24]:
obj.isnull().sum() # null 찾기 몇개니?

1

## 데이터프레임
- 2차원 배열, R의 데이터프레임에서 유래
- 열은 각각 시리즈 객체
- 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들의 값이 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(1 x m 행렬)는 m원소들의 단일 행행렬
- 리스트, 딕셔너리, ndarray 등 다야한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, ndarray 등으로 변환되 수 있음


In [4]:
import pandas as pd

In [5]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size = (3,3))
print(data, type(data))

df = pd.DataFrame(data, index = ['d1', 'd2', 'd3'], 
                  columns = ['pd', 'sales', 'inv'])
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [1]:
import numpy as np
np.random.randint(100,120, 9).reshape(3,3)

array([[104, 108, 109],
       [110, 109, 108],
       [101, 117, 109]])

In [37]:
# 인덱싱 : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1], '\n')
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int32 

pd       103
sales    103
inv      107
Name: d2, dtype: int32


In [38]:
# Q. iloc, loc 을 사용하여 107을 출력하세요

In [6]:
print(df.iloc[1][2])
print(df.iloc[1,2])
print(df.loc['d2', 'inv'])

107
107
107


In [8]:
df1 = df.copy()
df1

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [9]:
# d3의 값들을 모두 0으로 만드시오

In [52]:
df1.iloc[2] = 0 
df1

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [53]:
# 값들이 모두 0인 d4 행을 추가하세요

In [54]:
df1.loc['d4'] = 0 
df1

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [ ]:
# 열추가는 loc뺴고 그냥 하면 되는디

In [55]:
# 1행 1열의 값을 0으로 만드세요

In [57]:
df1.iloc[0,0] = 0
df1

pd  sales  inv
d1    0    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [62]:
# id, gender, age, region
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size = 1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size = 1000)
a1 = pd.Series(age)
region = np.random.randint(1, 11, size = 1000)
r1 = pd.Series(region)

df1 = pd.concat([i1, g1, a1, r1], axis = 1) # 적용
df1.rename(columns = {0:'id', 1:'gender', 2:'age' ,3:'region'},
         inplace=True)
df1.head() # 위 다섯행

id  gender  age  region
0   1       0   68       7
1   2       0   47      10
2   3       1   87      10
3   4       0   46       5
4   5       1   28       2

# 과제 : df1에 적합한 컬럼 5개를 추가하여 의미있는 데이터셋을 만드시고 그 데이터셋의 가치를 설명하세요.

In [ ]:
# 추가
# born = np.random.randint(1, 11, size = 1000)
# b1 = pd.Series(born)

# df1['born'] = b1


In [ ]:
# 데이터프레임 합치기
#df3 = pd.concat([df1, df2], axis = 1)  새로만들기? 재정의?

In [63]:
df2 = df1.copy()
df2.head()

id  gender  age  region
0   1       0   68       7
1   2       0   47      10
2   3       1   87      10
3   4       0   46       5
4   5       1   28       2

In [66]:
df2.iloc[0:2] = np.nan # null값 대입
df2.head()

id  gender   age  region
0  NaN     NaN   NaN     NaN
1  NaN     NaN   NaN     NaN
2  3.0     1.0  87.0    10.0
3  4.0     0.0  46.0     5.0
4  5.0     1.0  28.0     2.0

In [71]:
df2.isnull().sum()

id        2
gender    2
age       2
region    2
dtype: int64

In [70]:
df2.isnull().sum().sum() #총 갯수

8

In [78]:
# 1~4중 랜덤한 숫자로 구성되는 10행 5열 2차원 배열을 생성
np.random.seed(1)
f = np.random.randint(1,5, size=(10,5))
f

array([[2, 4, 1, 1, 4],
       [2, 4, 2, 4, 1],
       [1, 2, 1, 4, 2],
       [1, 3, 2, 3, 1],
       [3, 2, 3, 1, 4],
       [1, 3, 1, 2, 3],
       [3, 1, 4, 4, 2],
       [2, 4, 3, 1, 3],
       [2, 2, 2, 4, 4],
       [2, 3, 2, 2, 1]])

In [79]:
# 배열을 리스트로 변환

In [80]:
list1 = f.tolist()
print(list1, type(list1))

[[2, 4, 1, 1, 4], [2, 4, 2, 4, 1], [1, 2, 1, 4, 2], [1, 3, 2, 3, 1], [3, 2, 3, 1, 4], [1, 3, 1, 2, 3], [3, 1, 4, 4, 2], [2, 4, 3, 1, 3], [2, 2, 2, 4, 4], [2, 3, 2, 2, 1]] <class 'list'>


In [81]:
df1 = pd.DataFrame(list1, columns = ['c1','c2', 'c3', 'c4','c5'])
df1.head(3)

c1  c2  c3  c4  c5
0   2   4   1   1   4
1   2   4   2   4   1
2   1   2   1   4   2

In [82]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar, type(ar))

[[2 4 1 1 4]
 [2 4 2 4 1]
 [1 2 1 4 2]
 [1 3 2 3 1]
 [3 2 3 1 4]
 [1 3 1 2 3]
 [3 1 4 4 2]
 [2 4 3 1 3]
 [2 2 2 4 4]
 [2 3 2 2 1]] <class 'numpy.ndarray'>


In [83]:
li = ar.tolist()  # 여긴 붙여쓰고
print(li, type(li), '\n')
dict = df1.to_dict('list')  # 여긴 왜 띄어씀?
print(dict, type(dict))

[[2, 4, 1, 1, 4], [2, 4, 2, 4, 1], [1, 2, 1, 4, 2], [1, 3, 2, 3, 1], [3, 2, 3, 1, 4], [1, 3, 1, 2, 3], [3, 1, 4, 4, 2], [2, 4, 3, 1, 3], [2, 2, 2, 4, 4], [2, 3, 2, 2, 1]] <class 'list'> 

{'c1': [2, 2, 1, 1, 3, 1, 3, 2, 2, 2], 'c2': [4, 4, 2, 3, 2, 3, 1, 4, 2, 3], 'c3': [1, 2, 1, 2, 3, 1, 4, 3, 2, 2], 'c4': [1, 4, 4, 3, 1, 2, 4, 1, 4, 2], 'c5': [4, 1, 2, 1, 4, 3, 2, 3, 4, 1]} <class 'dict'>


In [96]:
# file 생성
file_data = pd.DataFrame({
    'col1':[1, 2, 3, 4, 5, 6],
    'col2':['A','A','B','B','C','C']
})
file_data

col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [97]:
file_data['col3'] = file_data.col1  #컬럼추가
file_data

col1 col2  col3
0     1    A     1
1     2    A     2
2     3    B     3
3     4    B     4
4     5    C     5
5     6    C     6

In [98]:
file_data.to_csv('dataset/file_data.csv', index = None)  # csv로 저장

In [99]:
file_data = pd.read_csv('dataset/file_data.csv')  #읽기 
file_data

col1 col2  col3
0     1    A     1
1     2    A     2
2     3    B     3
3     4    B     4
4     5    C     5
5     6    C     6

In [104]:
df_1 = pd.DataFrame({
    'col1':np.array([1, 2, 3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4, 5, 6]),
    'col2':np.array(['D','E','F'])
})

df_3 = pd.concat([df_1,df_2], axis = 1)  # 열추가
print(df_3, '\n')
df_4 = pd.concat([df_1,df_2]) # 행 추가 같은 컬럼명이니까 아래로 쭉 붙음
df_4

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F 



col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [106]:
# 열 삭제
df_5 = df_4.copy()
df_5 = df_5.drop('col1', axis = 1) 열
df_5

col2
0    A
1    B
2    C
0    D
1    E
2    F

In [108]:
# 행 삭제
df_6 = df_3.copy()
df_6 = df_6.drop([0], axis = 0)  # 디폴트값은 안써줘도 됨 axis = 0 행
df_6

col1 col2  col1 col2
1     2    B     5    E
2     3    C     6    F

In [111]:
df1

col1 col2  col3
0     1    A     1
1     2    A     2
2     3    B     3
3     4    B     4
4     5    C     5
5     6    C     6

In [110]:
df1 = file_data.copy()
df1[:3]

col1 col2  col3
0     1    A     1
1     2    A     2
2     3    B     3

In [112]:
df1[3:]

col1 col2  col3
3     4    B     4
4     5    C     5
5     6    C     6

In [113]:
df1[2:5]

col1 col2  col3
2     3    B     3
3     4    B     4
4     5    C     5

In [114]:
df1.iloc[-1]  # iloc 써줘야 먹음 음수슬라이싱 할땐

col1    6
col2    C
col3    6
Name: 5, dtype: object

In [125]:
#df1.loc[:,['col1', 'col3']]
df1[['col1','col3']]

col1  col3
0     1     1
1     2     2
2     3     3
3     4     4
4     5     5
5     6     6

In [126]:
df1.loc[1:3,['col1', 'col3']]

col1  col3
1     2     2
2     3     3
3     4     4

In [128]:
df1.iloc[1:3,0:]

col1 col2  col3
1     2    A     2
2     3    B     3

In [2]:
import numpy as np
import pandas as pd
np.random.seed(2)
data = np.random.randint(50, 100, size=(3,5))
df_e = pd.DataFrame(data, columns=list('abcde'))
df_e

a   b   c   d   e
0  90  65  95  58  72
1  93  68  61  90  57
2  84  99  81  61  71

In [4]:
df1 = df_e.copy()

In [5]:
df1.rename(columns={'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}, 
           index={0:'이상윤', 1:'강유한',2:'조승현'}, inplace=True)
df1

국어  영어  수학  과학  음악
이상윤  90  65  95  58  72
강유한  93  68  61  90  57
조승현  84  99  81  61  71

In [65]:
# 8행 5열 데이터프레임 생성
np.random.seed(1)
d = np.random.randint(50, 100, size=(8,5))
dff1 = pd.DataFrame(d, columns=list('abcde'))

dff1


a   b   c   d   e
0  87  93  62  58  59
1  61  55  65  50  66
2  51  62  57  95  56
3  75  70  87  68  70
4  61  92  78  79  64
5  54  73  73  91  99
6  80  82  72  63  91
7  59  57  72  51  50

In [60]:
# 열이름과 행이름 변경
dff.rename(columns={'a':'서울','b':'대전','c':'대구','d':'부산','e':'제주'}, 
           index={0:'1월', 1:'2월',2:'3월',3:'4월',4:'5월',5:'6월',6:'7월',7:'8월'}, inplace=True)
dff

서울  대전  대구  부산  제주
1월  87  93  62  58  59
2월  61  55  65  50  66
3월  51  62  57  95  56
4월  75  70  87  68  70
5월  61  92  78  79  64
6월  54  73  73  91  99
7월  80  82  72  63  91
8월  59  57  72  51  50

In [48]:
# 3행만 출력

dff.iloc[2, :]

서울    51
대전    62
대구    57
부산    95
제주    56
Name: 3월, dtype: int32

In [49]:
# 3행 5열의 값 출력
dff.iloc[2,4]

56

In [52]:
#4열의 값을 모두 0으로 변경
dff.iloc[:,3]=0
dff

서울  대전  대구  부산  제주
1월  87  93  62   0  59
2월  61  55  65   0  66
3월  51  62  57   0  56
4월  75  70  87   0  70
5월  61  92  78   0  64
6월  54  73  73   0  99
7월  80  82  72   0  91
8월  59  57  72   0  50

In [53]:
# 6행의 2,3,4열의 값을 조회
dff.iloc[5,1:4]

대전    73
대구    73
부산     0
Name: 6월, dtype: int64

In [54]:
# 2열을 Series와 DataFrame으로 각각 출력
#dff.iloc[:,1]
dff.iloc[:,[1]]

대전
1월  93
2월  55
3월  62
4월  70
5월  92
6월  73
7월  82
8월  57

In [55]:
# 2행 3열의 값을 2행 4열의 값과 동일하게 변경
dff.iloc[1,2]=dff.iloc[1,3]
dff

서울  대전  대구  부산  제주
1월  87  93  62   0  59
2월  61  55   0   0  66
3월  51  62  57   0  56
4월  75  70  87   0  70
5월  61  92  78   0  64
6월  54  73  73   0  99
7월  80  82  72   0  91
8월  59  57  72   0  50

In [68]:
df_s = dff1.copy()
df_s.rename(index={0:'r0',1:'r1',2:'r2',3:'r3',4:'r4',5:'r5',6:'r6',7:'r7'}, inplace=True)
df_s

a   b   c   d   e
r0  87  93  62  58  59
r1  61  55  65  50  66
r2  51  62  57  95  56
r3  75  70  87  68  70
r4  61  92  78  79  64
r5  54  73  73  91  99
r6  80  82  72  63  91
r7  59  57  72  51  50

In [73]:
#sort() 정렬

#df1_s = df_s.sort_index(ascending=False)
df1_s = df_s.sort_index()  # default 오름차순
df1_s

a   b   c   d   e
r0  87  93  62  58  59
r1  61  55  65  50  66
r2  51  62  57  95  56
r3  75  70  87  68  70
r4  61  92  78  79  64
r5  54  73  73  91  99
r6  80  82  72  63  91
r7  59  57  72  51  50

In [78]:
# 밸류값 정렬
df1_c = df1_s.sort_values(by='c', ascending=False)  # c의 열 정렬
df1_c

a   b   c   d   e
r3  75  70  87  68  70
r4  61  92  78  79  64
r5  54  73  73  91  99
r6  80  82  72  63  91
r7  59  57  72  51  50
r1  61  55  65  50  66
r0  87  93  62  58  59
r2  51  62  57  95  56

In [76]:
# 전치
df1_t = df1_s.iloc[:5,:]
df1_t # 5x5

a   b   c   d   e
r0  87  93  62  58  59
r1  61  55  65  50  66
r2  51  62  57  95  56
r3  75  70  87  68  70
r4  61  92  78  79  64

In [77]:
df1_t = df1_t.transpose()
df1_t

r0  r1  r2  r3  r4
a  87  61  51  75  61
b  93  55  62  70  92
c  62  65  57  87  78
d  58  50  95  68  79
e  59  66  56  70  64